### ISSUE TITLE
GLOSSARY - Procurement Procedure

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#113]
### New entry!!!

* Term: Procurement Procedure

* Definition: Lawful, organised and scheduled administrative tasks that allow one or more Procuring Entities the acquisition of works, supplies or services by means of a public contract.

#### Reason:

Currently, we don't have an entry for this concept in the glossary!

**Comment by JachymHercher** [comment]
I've spoken to one of our lawyers about this and he said that even though the directives don't define procedures, in his opinion a procedure would be anything leading to a "public contract" (as that is the central concept of the procurement directives). Thus I would rather propose a definition of something like:

"A series of activities aiming to conclude one or more public contracts." 

(I've updated the definition, because a procedure should be a procedure even if it fails; it can lead to one or more contracts)

**Comment by eprocurementontology** [comment]
Following the meeting of 5/09/2018 the term should be renamed procedure and the definition discussed on 7/09/2018

**Comment by eprocurementontology** [comment]
Term: Procedure
Definition: A series of  legally defined administrative steps conducted  to conclude one or more contracts. 

WG 07/09/2018 
The term public was removed as the ontology is about public procurement.  
It was noted that the ontology   does not include planning in the concept procedure
