### ISSUE TITLE
GLOSSARY - Criterion

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#121]
#### Current:

* Term: Criterion

* Definition: 

#### New: 

* Term: Criterion

* Definition: A broad condition that needs to be answered for evaluation purposes.

#### Reason:

In ePO we need a generic class and definition for Criterion.

**Comment by muricna** [comment]
WG approval 8/6/2018

**Comment by guascce** [comment]
The new definition agreed on 22/06/2018 is a condition that needs to be answered for evaluation purposes.
I would like to challenge the use of the word 'answered' because it implies a given process such as is in place in the ESPD. I would like the criterion concept to be used in a broader sense. For instance in order to specify requirements on products. In that case the condition would be met by the characteristics of the product for which evidence can be given through more means such as a label or a report or...

Can we change the definition then to "a condition that is stated for evaluation purpose"

**Comment by JachymHercher** [comment]
I very much agree with @guascce. The idea of "answering" sounds like something for selection criteria. For award criteria, where points would rather be given on the basis of an evaluation of the qualities/parameters described in the tender, it doesn't really apply.

**Comment by eprocurementontology** [comment]
WG approval 22/06/2018

Term: Criterion
Definition: A condition that needs to be answered for evaluation purposes.

Additional information/WG discussion points: For example:  General average turnover for the past three years.
This example is quoted in the example of the criterion property.

The glossary and the conceptual model have been updated accordingly on 06/07/2018.

**Comment by muricna** [comment]
To be discussed in today's (1/8/2018) conceptual model meeting to address the concerns of Cécile and Jáchym.  Meeting address: https://ecwacs.webex.com/meet/nmuric from 14h-16h.

**Comment by muricna** [comment]
In the current version 2.0.1 Criterion does not exist, only ProcurementCriterion exists.  Future versions are to take inspiration from the branch 2.0.2  where ProcurementCriterion inherits from Criterion from the Core Criterion and Core Evidence Vocabulary [CCCEV](https://github.com/SEMICeu/CCCEV)

**Comment by andreea-pasare** [comment]
The current version ePO 3.0.1 uses cccev:Criterion concept and has the definition aligned with the Core Criterion and Core Evidence Vocabulary, as follows:

_Condition for evaluation or assessment._

_Additional Information:
In general, Criteria are used for comparison, filtering or selection purposes. Criteria usually set minimum conditions (e.g. limits, intervals, thresholds, etc.) that need to be met in order to pass the requirements or to fulfil them to a certain degree or quality. The concept of Criteria is broader than the concept of Constraint since it covers more usages. The evaluation of the fulfilment is usually supported by the provision of Evidence. For example in the eProcurement domain, the eProcurement Ontology defines different subclasses of Criterion such as exclusion grounds, selection criteria or award criteria. A concrete example of a Criterion is 'participation in a criminal organisation' which could also be considered as an exclusion ground criterion in the procurement domain or for requiring a public service._
