### ISSUE TITLE
Glossary - eCatalogue

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#132]
Dear Natalie

The e-catalogue part is not correct. It mixes different things. I her attach the definitions made in WG05 as suggestions. I just changes a bit to align with the directive (red)

(SJ) e-catalogue                                                  A catalogue of supplies and services defined by one or more identifiers.                          

(WG05) Pre-award catalogue (request)	A catalogue of requirements (on products (goods or services)) supplies and services intended to be bought by a Contracting Authority.
(WG05)Pre-award catalogue request identifier	

An identifier for the pre-award catalogue request that allows referencing the pre-award catalogue request.

I would suggest to discuss this with Veit Jahns too. 

Med venlig hilsen / Best regards

Søren Jensen

**Comment by idolum** [comment]
Yes, I agree that current definitions is very unspecific, in particular if it comes to a catalogue that is intended to describe offered goods and services. But I do also not fully agree with Søren's proposal. So, I am available for discussing the definition(s).

**Comment by idolum** [comment]
Dear Natalie,

unfortunately, I could not participate in the meeting where you discussed this term. But I have some remarks to the summary you shared:

* Based on the summary, I could not figure out which definition you choosed in the meeting. But I would prefer a definition that is related to the one given in the CWA 17028 series. Furthermore, there are various definition given in the scientific literatur that could be used and adapted for our purposes.
* I would prefer not to mix the terms catalogue and catalogue request, in particular in the pre-award area. Because, here (pre-award catalogue requests are not just catalogues without prices, but a specification of requirements on the products to be tendered. I.e., the specifications in the catalogue request should be vendor-neutral (in terms of that classes of goods/services are specified), and thus located on a different level of abstraction as catalogues. Cf. also CWA 17028-402:2016 (Guideline on Pre-award Catalogues).

Best regards

Veit

**Comment by muricna** [comment]
eCatalogue: A document describing a set of items offered for purchase that can be processed in an electronic way.

WG approval 23/03/2021
