### ISSUE TITLE
clarifications on Procurement Project definition and modeling pattern with Procedure & Lot

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#134]
Dear all,

in Italy we are looking with interest to the data model you are creating. Specifically, we are creating the Italian PublicContract Application Profile using semantic web standards.
We did not find a proper definition of the Procurement Project entity. In the glossary there is no definition, to the best of our knowledge.
What do you exactly mean with that entity? May I kindly ask you an example of data modelled with that entity too?

In addition, could you please clarify the modeling pattern where ProcurementProcedure and Lot are subclasses of ProcurementProject disjount with each other, and for the ProcurementProcedure there exists at least one Lot?

Thanks a lot in advance.
Best Regards,
Giorgia Lodi

**Comment by muricna** [comment]
Hello,

Glad to hear you are joining our discussions.  The reason why the glossary does not have a clear definition is that we are going through the glossary alphabetically and making each term as clear as possible.  With regard to the modelling between Procurement project, lots and procurement project.  Can I suggest that you join one of our glossary conceptual model meetings that take place every Wednesday from 14-16h.  We have a meeting tomorrow and then have a 2 week break to start again on 29/08/2018 until 19/08/2018.  The address of the meeting is https://ecwacs.webex.com/meet/nmuric.  Of course you are welcome to come to all the meetings if you wish.

**Comment by giorgialodi** [comment]
Dear @muricna 

thanks for your prompt reply and the engagement invitation. It is likely that we will partecipate starting from the end of August. Most of us, working on this, are currently off on summer holidays :)

BR,
Giorgia

**Comment by JachymHercher** [comment]
I'm also very curious to see the definition of the procurement project. 

@muricna, the project was already discussed during the 25th July call, no? Will ti be discussed again? Personally, the usual summary on GitHub would be enough for me - and I kind of expected it to come in the coming days?

**Comment by muricna** [comment]
Please find below the summary of the meeting of 25 July which was sent to the mailing list.  If you wish in the future the summaries can also be put on the github:

During this meeting we discussed the Procurement project and Procurement procedure models.  It was explained and agreed that the procurement project is the base for lots and the procurement procedure, all procedures having at least one lot.  The property “Jurisdictional level “ should be renamed.  “Jurisdiction” refers to the power of a court of law,  whereas this property is meant to describe the level of legislation ie International, European, National, Regional, Local.  This should also be a code list rather than text.  Suggested terms for this property are Legislative level and Applicability level.  When creating the code list the code list team should verify the terminology with a lawyer.

Likewise the term Jurisdictional Competency level is wrong in the procuring entity model, it was agreed the term already used in TED Authority should be used.

It was agreed that techniques and documents could not be covered by code lists since code lists are composed of simple data types ie the individual entries for the codes cannot have properties themselves. 

We could discuss these points in the meeting of 5 September from 14h-16h at https://ecwacs.webex.com/meet/nmuric
