### ISSUE TITLE
Shouldn't the Electronic Submission property be a "submission term"?

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#154]
The property "electronic submission" is now in class "Tender"....right now it seems more natural to me that it went into the class "Submission Terms"...but I have a kind of "déjà-vu" and possibly it was there and we decided to move it into the Tender class?

**Comment by muricna** [comment]
The reason for it being in submission terms is that it is to indicate that submission is to be made electronically

**Comment by everis-rpam** [comment]
But right now is not there!

**Comment by muricna** [comment]
The electronic submission is represented.  In the Procedure Terms model: "Submission Terms +eSubmission Communication "Persmission".

What does  the + in the eSubmission Communication mean?

There is a discrepency between  the eforms and ontology to be discussed.  eforms forsees a code list with the follow values:
required	
allowed
not-allowed	
ontlogy forsees authorised instead of allowed.

**Comment by jseguraf** [comment]
The "+" is created automatically by the EA when an attribute is created. All the attributes have been checked in order to be consistent. 

Moreover, the permission code list has been updated with the inclussion of the "Allowed" term.
