### ISSUE TITLE
Add [Pre-]Qualification System (PQS) to the model

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#169]
Pre-Qualification System should be added to the ePO Conceptual Model.

**Comment by paulakeen** [comment]
This should be done when analysing e-Submission, as the PQS plays a special role when the Economic Operator prepares the ESPD Response, which is a document that is part of its tender.

**Comment by JachymHercher** [comment]
When modelling, please note that a pre-qualification system and a dynamic purchasing system are functionally very similar.

**Comment by jpmckinney** [comment]
@JachymHercher I am not sure that a QS and a DPS should be modelled the same way.

A QS is more like a supplier list. To procure from those suppliers, a new procedure must be initiated (restricted procedure or negotiated procedure per Art. 77 of 2014/25/EU).

In a DPS (which is essentially a framework agreement to which new suppliers can join at any time), the procurements / call-offs are made as part of the same procedure.

Also, although buyers' needs and other details are fairly loosely expressed when establishing a DPS (compared to when establishing a framework agreement), they are still more detailed in a DPS than in a QS (by my understanding).

**Comment by SellittoGiampaolo** [comment]
And moreover, nowadays pre-qualification systems are more intended as lists of EOs that have been scrutinized and recognized as capable of executing contracts of a specified category and up to some value (based on previous contracts and technical capabilities) 
What should be clear is that the enrollment in some pre-qualification system does not imply the fact that all of the Exclusion Grounds  are still valid given the pre-qualification. What is assessed by the prequalification is more the technical and financial capability of the Economic Operator.
In this sense the result of the pre-qualification scrutiny are very similar to the results of the the DPS scrutiny.
Yes, usually new Economic Operators can join both the pre-qualification system and the DPS if they have the capabilities and in both cases the Contracting Authorities should check the absence of Exclusion Grounds when awarding specific contracts. 
This specific point is not clear to many contracting authorities, resulting in the award of a contract based only on the enrollment in the pre-qualification system  (capabilities).

**Comment by jpmckinney** [comment]
(Noting that EG stands for exclusion grounds – took me a minute to figure it out from context.)

**Comment by SellittoGiampaolo** [comment]
Sorry, I was on the rush and used the acronym - I have updated the post

**Comment by JachymHercher** [comment]
@jpmckinney Hard to say, I honestly do not know what is the best approach. What you are saying _might_ be right. However, the plural "procedure*s*" in Art. 77(5) might also just be bad phrasing / strange use of the plural (where the legislator's intention was to say "in general, QS shall be a restricted or negotiated procedure). To resolve this, I think one would need to have a step-by-step look at a few examples of actual QS procedures in different MS. 

Few thoughts:
- All procedures (except direct awards) "start" by publishing a notice that is a call for competition (see e.g. the overview in Art. 44(4) of Dir. 2014/25/EU). If we read Art. 77(5) of Dir. 2014/25/EU literally, then the QS would be different: there would be a notice which is a call for competition, but it wouldn't "start" the procedure yet, because those would be launched later on. 

    If we do not read it literally, then the QS looks more like a DPS (at least from the point of view of what data is published): you publish a call for competition ( = launching the procedure), you do not publish anything about the mini-competitions, you publish the contract award notice.

- I can't exclude that national legal opinions/implementation differ even on matters such as whether DPS is actually a procedure. In eForms, it is treated as a restricted procedure, because of Art. 52(2) of Dir. 2014/25/EU says that "In order to procure under a dynamic purchasing system, contracting entities shall follow the rules of the restricted procedure." However, I had a (short) exchange with an Austrian lawyer and I got the impression that in Austria, DPS is perhaps not a procedure per se, bust just "something" that "follows" the same rules. 

- If the plural in Art. 77(5) was really correct, I still wouldn't know whether within a single QS you can still only have multiple procedures of a single type (e.g. all restricted) or whether you can mix both. (eForms and the current TED forms do not have any opinion on this, as neither includes Procedure (BG-6) in the QS notice). 

From a data modelling point of view, I think we should try to concentrate on the "functional purpose" of a given step (and e.g. ignore idiosyncratic naming). The fact that "procedure", the centerpiece of procurement, is not defined anywhere doesn't help though :).

**Comment by jpmckinney** [comment]
> I can't exclude that national legal opinions/implementation differ even on matters such as whether DPS is actually a procedure. In eForms, it is treated as a restricted procedure, because of Art. 52(2) of Dir. 2014/25/EU says that "In order to procure under a dynamic purchasing system, contracting entities shall follow the rules of the restricted procedure." However, I had a (short) exchange with an Austrian lawyer and I got the impression that in Austria, DPS is perhaps not a procedure per se, bust just "something" that "follows" the same rules.

Isn't DPS a "technique" in eForms? I think opinions differ, because in some jurisdictions, they never have multiple FAs or DPSes in a single procedure, so it is easy to conflate procedure with technique. However, in most of my conversations, when asked to consider a procedure with multiple lots that sets up one FA per lot, people acknowledge the difference.

> eForms and the current TED forms do not have any opinion on this, as neither includes Procedure (BG-6) in the QS notice

This would support the idea that a QS is not a procurement procedure, per-say, but rather a way to build a supplier list, that can then be used in later procedures.

> From a data modelling point of view, I think we should try to concentrate on the "functional purpose" of a given step (and e.g. ignore idiosyncratic naming). The fact that "procedure", the centerpiece of procurement, is not defined anywhere doesn't help though :).

I agree in general. However, I think there is a risk of "over-normalizing". Even if the line between a procedure and a part of a procedure is arbitrary in many cases, it is still important for a data model to be able to give expected answers for questions like "how many procedures were unsuccessful this year", etc.

**Comment by JachymHercher** [comment]
> Isn't DPS a "technique" in eForms?

Yes. I wasn't precise, sorry - it's not about whether a DPS "is" a procedure, but rather whether using a DPS "happens" within a procedure or not. 

> This would support the idea that a QS is not a procurement procedure, per-say,

I'm not sure. It can also just reflect that since QS are a long term set up, you don't yet know which type of procedure (or which type of mini-competitions...) you will use? 

> it is still important for a data model to be able to give expected answers for questions like "how many procedures were unsuccessful this year", etc.

I agree. In other words, one would need to know whether the "procedure(s)" following a QS are conceptually more similar to separate "procedures" following separate notices, or to mini-competitions following an FA/DPS. Besides the qualitative checking mentioned above, one could also analyze the patterns in the TED data. For example, if a QS notice is typically followed by 100s of contracts, I would argue it looks like a DPS; if typically by one, it's essentially a simple negotiated/restricted procedure; if typically by a few (2-10?) then perhaps it's a special case? 

(I opened a few notices at random and found QS which were [simple](https://ted.europa.eu/udl?uri=TED:NOTICE:489108-2018:TEXT:EN:HTML&src=0&tabId=4), [simple with annual renewal](https://ted.europa.eu/udl?uri=TED:NOTICE:51905-2018:TEXT:EN:HTML&src=0&tabId=4), [special](https://ted.europa.eu/udl?uri=TED:NOTICE:30221-2017:TEXT:EN:HTML&src=0&tabId=4) (2 CANs following a QS), and [strange](https://ted.europa.eu/udl?uri=TED:NOTICE:414168-2019:TEXT:EN:HTML&src=0&tabId=4). Still, you'd need to look at all the data to be able to make a conclusion.)  

(Pet peeve: I advocate for avoiding procedures (and any metrics linked to them) as much as possible. What matters is the competition _per lot_ / _per contract_; money spent _by X_, _on Y_, _with Z_. I think that "procedure" is very rarely the appropriate level of analysis and it's used because it comes to mind first and people don't realize how fraught it is.)

**Comment by jpmckinney** [comment]
Agreed on the pet peeve. A model that more dramatically re-organizes source information would probably be more valuable to users than one that more closely follows arbitrary distinctions that particular procurement regimes make.

To date, however, most modelling efforts have balanced toward resembling existing data structures, perhaps to keep things familiar to potential adopters and/or to allow for a mechanical 1-to-1 mapping from procurement systems, and thereby avoid intellectual challenges.

**Comment by andreea-pasare** [comment]
In ePO v4.0.0-rc.1 there is no use case for presenting the further criterion used during the Mini Competitions, nor is the candidate list published, only the Selection and Exclusion Criteria of the originating Lot are published in the Contract Notice.

If a use-case for providing this information is requested, the ePO model can be evolved.
