### ISSUE TITLE
Cardinalities - properties and attributes

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#187]
The cardinalities of properties and attributes should be removed as their cardinalities could be different under different phases. The cardinalities should be treated in the Application Profiles. Certain properties and attributes should however be noted as mandatory. 

WG decision 09/01/2018

**Comment by JachymHercher** [comment]
This is a very important question which is linked to the way the ontology should be used in the future. The approach suggested above is not 100% clear to me. 

1) I assume "[application profiles](https://en.wikipedia.org/wiki/Application_profile)" means profiles for individual e-procurement systems implementing the ontology. However, will there be many systems directly implementing the ontology? Won't it typically be implemented rather through other standards (e.g. eForms, ESPD), in which case the cardinality gets specified in these intermediary artifacts?
2) If this information really got specified in the application profiles, wouldn't that severely undermine their interoperability, one of the main goals of the ontology? 
3) Isn't cardinality sometimes the reason for the conceptual model being the way it is? For example, a class is separated from another class because the former is repeatable, the latter not? If yes, then removing cardinalities will reduce clarity.
4) Many of the very detailed and technical discussions of the working group include a discussion on cardinality. Wouldn't we lose a lot of information and reduce the usefulness of the ontology by cutting this information out?

As an alternative approaches, we could, for example: 
- Give the most general cardinality, across all phases (i.e. if the information/link does not need to exist in at least one stage, then it is indicated as 0..; if it can be repeated in at least one stage, it is indicated as ...n). 
- Provide cardinalities per stage in an additional document, which would still be part of the ontology. 
- At least provide illustrative cardinalities for one selected stage (e.g. eNotification).

**Comment by jpmckinney** [comment]
At the February in-person meeting, there seemed to be general agreement that some cardinalities are useful, if not fundamental, to understanding the ontology.

It makes sense for application profiles to set specific limits like "no more than 1,000 lots per procedure". But cardinalities like 0-1, 1-1, 0-n, 1-n are very basic parts of a model.

For example, would it make any sense for a lot to have multiple procurement values? for a contract to have multiple periods? They each should only have one.

Creators of application profiles shouldn't have to wrestle with questions about what the law allows in terms of cardinalities, whether it is possible for a lot to have multiple purposes, etc. If they are required to do so, then I am sure they will make conflicting and non-interoperable design decisions.

I don't see any advantage to omitting such cardinalities, besides a sense of theoretical purity. They merely describe the nature of the relationship between two items, without interfering with whatever restrictions an application profile might want to impose.

**Comment by eprocurementontology** [comment]
The UML convention, as used in EA for example, is that if no cardinality is specified then it is 1..1. At implementation time this may introduce a lot of confusion as many of cardinalities of the attributes are specified and are optional. 

In principle, if we want to be flexible (i.e. standard-oriented), this should be just the opposite: if no indicated then all attributes should be optional. And then for application profiles the cardinality should be specified.

**Comment by jpmckinney** [comment]
If the convention is 1..1, then surely we want to specify the cases where the cardinality is not 1..1 but 0..1, 0..n or 1..n?

By "optional", do you mean to suggest a convention of 0..1, or do you mean 0..n?

..1 versus ..n has major implications in terms of how the ontology is understood, and therefore in terms of how applications are designed; I think at least that much should be specified.

I am very supportive of flexibility, but we don't need to be flexible beyond the limits of possibility and reality. The ontology, after all, is about putting some sense (and limits) to the world.

**Comment by JachymHercher** [comment]
Please do not forget to re-open this issue.

**Comment by jseguraf** [comment]
We agree. We will specify the cardinalities in the attributes, this will be finalized after holidays.

**Comment by muricna** [comment]
The cardinalities were addressed in the v2.0.1 of the model
