### ISSUE TITLE
DPS Termination

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#198]
Could the indicator in the Procedure class  be reused also for the DPS? and therefore, could the attribute DPS Termination be removed from "Dynamic Purchase System"?

**Comment by JachymHercher** [comment]
From a modelling point of view, "DPS termination" and "Procedure based on a PIN CFC" could indeed be covered by one attribute/class (and still be perfectly mappable to eForms). In eForms, they are separated mainly to make the information more visible and clear - DPS and procedures based on a PIN CFC are quite different. Also, we think it's clearer to have an indicator on DPS termination next to the other DPS-related fields. 

Please note that since the point of these fields is informing the market about business opportunities that are still ongoing, it should be possible to specify the information per lot, not just per procedure. For DPS, this could be the case e.g. when the budget for a lot/category is exhausted or the requirements/criteria have changed. For the procedure based on PIN CFC this is a bit more theoretical, but still possible. 

In practical terms, in eForms & TED, the impact of these elements being yes would be that the relevant (lots of) notices would no longer show in the search results when the user is looking for "currently open opportunities."

**Comment by andreea-pasare** [comment]
This is related to #358 
![image](https://github.com/OP-TED/ePO/assets/88081600/22f09180-abfc-4e5c-ac2a-a7e1a75155c3)
