### ISSUE TITLE
Tender & Tender Lot vs. other comparable (?) situations (e.g. Submission Terms)

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ePO#204]
In the current version of the ontology, there is a class for Tender Lot and a class for Tender. The difference between them is that Tender Lot contains information which only applies to a lot. 

Isn't this inconsistent with many other areas of the ontology (e.g. Submission Terms), where some information in a class applies to a whole procedure (= all lots?), while other information in the same class may apply only to a specific lot? 

(One particularity is that, in practice, Tender will probably always have a Tender Lot - it is unlikely that a tenderer would offer the same price for multiple lots. However, I'm not sure this difference is "conceptual" enough to model the two situations differently.)

**Comment by paulakeen** [comment]
1. The Tender Lot is the information that the EO provides about the Lot(s) it tenders to (e.g, and very important, the "Financial Offer Value" for one specific Lot). The "Tender Lot" is thus part of the Tender.

2. Sorry @Jachym, but in the ontology the Submission Terms apply to one or more Lots, not to the whole Procedure. See diagram:

![JachymAndHisLots](https://user-images.githubusercontent.com/16134316/60895604-3a98cd80-a265-11e9-81fa-67a3bb645bf3.png)


3. Because i) Procedures with no Lots have always one Lot, the Tenderer can specify a global price for the whole Procedure by assigning the  price (i.e. the Financial Offer Value) to the Tender Lot; and ii) precisely because the Tender Lot is representing the offer by the EO for each Lot, prices are clearly separated given that (as you say) the EO very unprobably will charge the same price to multiple lots.

But may be we're not understanding the last part of your comment....

**Comment by JachymHercher** [comment]
1) That's clear. 
2) Sure (I'm not sure it's clear from the image though). However, Submission terms [can apply to multiple lots](https://eprocurementontology.github.io/CDM_Report/HTML/index.htm?goto=23) and if they apply to all lots in a procedure, then they - de facto - apply to a whole procedure. 
3) That's clear. 

To rephrase my concern: 

In Tender & Tender Lot, we have properties such as Electronic Submission, Non Electronic Submission Justification, Variant, Financial Offer Value, etc. 

In [Submission Terms](https://eprocurementontology.github.io/CDM_Report/HTML/index.htm?goto=23), we have properties such as Submission Document Type, Receipt Deadline, Tender Validity Deadline, Document Language, etc. 

In both cases, there are plenty of properties that sometimes apply to all lots, sometimes to only some lots (e.g. Variant, Financial Offer Value, Receipt Deadline, Tender Validity Deadline, Document Language). 

_If I understand correctly, the only reason why we differentiate Tender from Tender Lot (but not Submission Terms from Submission Terms Lot) is that in the case of tenders, some properties always apply to all lots ([e.g. Electronic Submission, Non-Electronic Submission Justification](https://user-images.githubusercontent.com/16134316/60895604-3a98cd80-a265-11e9-81fa-67a3bb645bf3.png))._ 

My doubts:
i. Is this a sufficient reason to have a separate class? Since properties in Tender Lot could apply to all lots and thus, de facto, to the whole procedure, wouldn't it be simpler to have everything in "Tender Lot"? (Because, in a given instance of Tender and Tender Lot data, all properties in Tender and some properties of Tender Lot will apply to all lots.)
ii. Are you sure that, in case of tenders, some properties really _absolutely always_ apply to all lots? For example, looking at the reasons for non-electronic submission given in Art. 22 of Directive 2014/24/EU, couldn't it be the case that, for a works contract, one lot will require the submission of a scale model ("bridge design"), while another lot will be submitted normally ("works for building the bridge"); or, for example, one lot contains sensitive information but another does not? (I agree that both are hypothetical, 0.00001% cases, but still.) 
iii. Are you sure that in, for example, Electronic Submission, there aren't any properties that really absolutely always apply to all lots? For example, in a given notice, won't Submission Document Type be the same for all lots? (Because if the procedure is open, then the document is a tender; if the notice is two-stage, the documeent must be a request to participate; if the notice is a PIN CFC, the document must be an expression of interest?).

**Comment by eprocurementontology** [comment]
The next version of the ontology will remove TenderLot
