### ISSUE TITLE
Concept Regime not used in eForms yet seeming useful, so why is it not used?

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#217]
In the ontology we would like to create a legal regime enumeration for a property 'has legal regime' to a legislation that is the legal basis of a procedure.
the possible values would be 
a.	‘none’
b.	‘light regime’ or ‘Social and specific services’
c.	‘Design contest’

**Comment by JachymHercher** [comment]
We have joined "Legal Regime" with "Notice Type". This approach seems simpler than having separate codelists, because otherwise you would need to have many more business rules describing which notice type may / may not be combined with a particular Legal Regime. (That concerns the light regime, for design contest, the mapping is straighforward - 1-1.) 

Here's the codelist: 


Business Term | Draft list of   what is to be covered by the codes | Additional   information
-- | -- | --
Notice   Type | Notice of the publication of a prior information notice or a   periodic information notice on a buyer profile | See Art. 48(1) of Directive 2014/24/EU, Art. 67(1) of   Directive 2014/25/EU, Art. 30(1) third subparagraph of Directive 2009/81/EC
  | Prior information notice or a periodic indicative notice used   only for information | See Art. 48(1) of Directive 2014/24/EU, Art. 67(1) of   Directive 2014/25/EU, Art. 30(1) of Directive 2009/81/EC
  | Prior information notice or a periodic indicative notice used   to shorten time limits for receipt of tenders | See Art. 27(2) of Directive 2014/24/EU, Art. 28(3) of   Directive 2014/24/EU, Art. 45(2) of Directive 2014/25/EU, Art. 33(3) of   Directive 2009/81/EC
  | Prior information notice or a periodic indicative notice used   as a call for competition –  **standard   regime** | See Art. 48(2) of Directive 2014/24/EU, Art. 67(2) of   Directive 2014/25/EU
  | Prior information notice or a periodic indicative notice used   as a call for competition –  **light   regime** | See Art. 75(1)(b) of Directive 2014/24/EU, Art. 92(1)(b) of   Directive 2014/25/EU, Art. 31(3) of Directive 2014/23/EU
  | Notice on the existence of a qualification system | See Art. 68 of Directive 2014/25/EU, Art. 92(1)(c) of   Directive 2014/25/EU
  | Contract or concession notice – **standard regime** | See Art. 49 of Directive 2014/24/EU, Art. 69 of Directive   2014/25/EU, Art. 30(2) of Directive 2009/81/EC, Art. 31(1) of Directive   2014/23/EU
  | Contract notice – **light regime** | See Art. 75(1)(a) of Directive 2014/24/EU, Art. 92(1)(a) of   Directive 2014/25/EU
  | Subcontracting notice | See Art. 52(1) of Directive 2009/81/EC
  | Design contest notice | See Art. 79(1) of Directive 2014/24/EU, Art. 96(1) first   subparagraph of Directive 2014/25/EU
  | Voluntary ex-ante transparency notice | See Art. 3a of Directive 89/665/EEC, Art. 3a of Directive   92/13/EEC, Art. 64 of Directive 2009/81/EC, Art. 3a of Directives 89/665/EEC   and 92/13/EEC
  | Contract or concession award notice – **standard regime** | See Art. 50 of Directive 2014/24/EU, Art. 70 of Directive   2014/25/EU, Art. 30(3) of Directive 2009/81/EC, Art. 32(2) (reference to   Annex VII) of Directive 2014/23/EU
  | Contract or concession award notice – **light regime** | See Art. 75(2) of Directive 2014/24/EU, Art. 92(2) of   Directive 2014/25/EU, Art. 32(2) (reference to Annex VIII) of Directive   2014/23/EU
  | Design contest result notice | See Art. 79(2) of Directive 2014/24/EU, Art. 96(1) second   subparagraph of Directive 2014/25/EU
  | Contract modification notice | See Art. 72(1) of Directive 2014/24/EU, Art. 89(1) of   Directive 2014/25/EU, Art. 43(1) of Directive 2014/23/EU
  | Change notice | Used to change any of the notices listed above.

**Comment by paulakeen** [comment]
The WG agrees that having an ad-hoc enumeration of regimes associated to the legal-basis adds complexity to the model and the processes. The simplification proposed by eForms of having the regimes in the contract notice type seems a simpler solution. So we adopt the solution proposed in eForms and will ask for enriching the Contract Notice Type code list with the regimes, as in the example provided by Jachym.

As this has to be aligned with the current ongoing work on codelists, we keep this issue open for further discussion on how the codes would be encompassed in the Contract Notice Type codelist.

**Comment by eprocurementontology** [comment]
The different legal regimes are semantically different from the notices we therefore suggest to keep the current solution however we need to find a solution for the epo Code lists: they should be published officially.
