### ISSUE TITLE
Legal basis relates to procedure, why not lot?

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#218]
In the contract notice , the legal basis relates to procedure and not to lot, when the directive has more articles (3, 16, 17) that express th epossibility to choose more legal regimes corresponding to more legal basis.
What is the reason for e-forms not to define legal basis per lot?

**Comment by JachymHercher** [comment]
Just a quick answer (we can come back with a slow answer later on): I suggest taking it as an axiom. Please note that the Directives are not really consistent in their use of the words "contract" and "procedure" (as well as singulars and plurals, taking into account lots, etc.). So in the Articles you mentioned - which I just skimmed right now - I would say "contract" rather means "procedure".

(From there on, the Directives say quite clearly that if you have a single mixed contract, only one Directive applies. E.g. "Where contracting authorities choose to award a single contract, this Directive shall, unless otherwise provided in Article 16, apply to the ensuing mixed contract, irrespective of the value of the parts that would otherwise fall under a different legal regime and irrespective of which legal regime those parts would otherwise have been subject to.")

**Comment by paulakeen** [comment]
We currently have the legal basis linked to Procedure. After discussion the WG agrees that keeping it like this is a more practical approach than having to calculate/suggest the legal approach from different legal-basis attached to specific lots.

This also would align the ePO to eForms. Thanks Jachym.

We close the issue.
