### ISSUE TITLE
BT-766; Dynamic Purchase System; Description and dps-usage codelist

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#223]
According to the description of the BT-766, the dps-nlist code should refer to CPB, and does not (please see the definition of the code and compare with the BT description).

The ePO WG considers that there are possibly several concepts that are combined into one single BT, and that in the eForms designing method should may be end up in different codes? e.g. in the description you mention:

1) the use or not of the DPS
2) that the buyer is a CPB or not
3) what to do with the lists of buyers

Or is it that there is a business rule implying that this code list can only be used when DPS and CPB are both involved?

**Comment by JachymHercher** [comment]
Answer to the last question - yes. :)  More in detail below: 

The code list is:
- Dynamic purchasing system, only usable by buyers listed in this notice
- Dynamic purchasing system, also usable by buyers not listed in this notice

The second code is only usable if one of the buyers has an Organisation Role (BT-8) equal to CPB. This is covered by a business rule. We did not include it in the definition, as we rather considered to be a "legal background" type of thing.

**Comment by jseguraf** [comment]
The 30th September and 1st October - new session to map the eForms terms with the ePO Ontology within the context of Contract Notice. In this session, the following modelling decisions were made. Please note that the mapping and the modifications have been implemented in the Contract Notice diagram:
 
•	BT-766 Dynamic Purchase System. The WG was discussing the issue #223 about how to deal with the combination of heterogeneous elements in one code list such as DPS, CPB, lists of buyers (see https://github.com/eprocurementontology/eprocurementontology/issues/223)
•	BT-13712. It is covered through the Lot ID, Lot uses ElectronicMeansofCommunication.
•	BT-127 Future Notice. It is just for planning therefore is not needed for the Contract Notice. 
•	BT-631 and BT-130. EstimatedInvitationToTender has been created as an attribute of the multiple-stage class. Dispatch Invitation Tender is no need since we are in the Contract Notice context. It is used in sed in PINs CFC.
•	BT-99. It is covered through the "review deadline information" attribute within the "review terms" class. In addition a new definition for the attribute has been created: The description of the time limits for review procedures.
•	The class review terms has been dropped within the contract notice diagram. 
•	The Procurement Document has been dropped within Contract Notice diagram and it has been linked to Lot through the property "referredToIn".
•	 The documentreference class has been created within the UBL package and the Document class inherits from this one.
