### ISSUE TITLE
BT-08; organisation role + code list

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ePO#224]
I was checking the Finnish translations but this may be applicable to original versions, as well.

This may also be intentional and not a bug.

BT-08 says that all organisations involved need to be mentioned in all notices. 

A CPB publishes a contract notice. There are 300 organisations that may use, let’s say, a framework agreement. I does make sense that all the 300 organsiations would be mentiond in the contract notice (even though it's bit laborious to list all).

**Does the description mean that also in this case all organisations need to be included in the contract notice?** 

If yes: there is no clear identifier on the code list for these types of organisations (apart from buyer).

**There is also BT-111 in the eForms.**

How should this be interpreted in conjunction with BT-08.
Is this the place for the 300 organisations in my example? Or does this mean that this only concerns additional organisations that are not listed in BT-08?

**Comment by JachymHercher** [comment]
This is applicable to eForms in general, its not a question of the Finnish translation. 

The requirement to identify all buyers in a contract notice is in force already now, see e.g. Art. 33(2), second subparagraph of Directive 2014/24/EU. As discussed in https://github.com/eForms/eForms/issues/30, this can indeed either be done one by one via BT-08 or through BT-111. The intention of BT-111 is to cover those that are not already listed via BT-8, but if there was an overlap, it probably doesn't cause any harm. 

(You are right that in BT-08 the descriptions of "all organisations" could have read "all organisations except, in case of framework agreements, those falling withing categories listed in BT-111", but hopefully this imprecision for the sake of simplicity doesn't cause too much confusion.)

Listing organisations in full detail using BT-08 means better data quality, but requires some technology to make it feasible if there are many buyers - see e.g. paragraph 4 of https://github.com/eForms/eForms/issues/266#issuecomment-473699693. (You might find the whole conversation interesting.)

In the codelist are the organisations you mention would fall under "buyer" - because they are all contracting authorities. Please note that if so desired, in any contract award notices announcing contracts within framework agreements, you can link an individual buyer to an individual contract using Organisation Notice Section Identifier (BT-13720).
