### ISSUE TITLE
BT-124 Atypical Tool URL

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#225]
In the ePO WG meeting we are trying to understand how this concept is used and in which circumstancies. We have concluded that this refers to what is mentioned in Directive 24 in recitals 53 to 56.  If so, what you name atypical we understand it as non-standard or "ad-hoc" tools (e.g. for secure and dedicated communications, non-standard catalogues, other).

Please help us to understand how eForms intends to use this.

**Comment by JachymHercher** [comment]
The field is included because it is required by Art. 22(5) of Directive 2014/24/EU. ("The text of the notice or the invitation to confirm interest shall specify the internet address at which those tools and devices are accessible.")

We've checked current TED notices and, honestly, didn't find any examples of correct usage of the field. It's not used practically at all and when it was, it gave links to tools that seemed fairly typical. Consequently, I wouldn't spend too much time on it... 

(Two hypothetical examples of what could be there are in https://github.com/eForms/eForms/issues/226.)

**Comment by eprocurementontology** [comment]
The end point in channel is used for this purpose.
