### ISSUE TITLE
Green Procurement Definition

### ISSUE THREAD

**Issue by jseguraf** [OP-TED/ePO#230]
Proposed definition:

Approach whereby public authorities seek to procure goods, services and works with a reduced environmental impact throughout their life cycle when compared to goods, services and works with the same primary function that would otherwise be procured.

Additional Information: 
Tightly related are article 68 - Life-cycle costing and article 67 - most economically advantageous tender (see GPP handbook) https://ec.europa.eu/environment/gpp/pdf/Buying-Green-Handbook-3rd-Edition.pdf
An instance of the class GreenProcurement is represented in eForms with the code "env-imp" defined in the codelist strategic-procurement.

**Comment by eprocurementontology** [comment]
Approach whereby buyers seek to procure with a reduced environmental impact.

Additional Information:

The approach may apply to the complete life cycle. The reduced environmental impact is in comparison to goods, services and works with the same primary function that would otherwise be procured.

Tightly related are article 68 - Life-cycle costing and article 67 - most economically advantageous tender (see GPP handbook) https://ec.europa.eu/environment/gpp/pdf/Buying-Green-Handbook-3rd-Edition.pdf An instance of the class GreenProcurement is represented in eForms with the code "env-imp" defined in the codelist strategic-procurement.paragraphs) https://ec.europa.eu/environment/gpp/pdf/Buying-Green-Handbook-3rd-Edition.pdf

WG approval: 10/03/2020
