### ISSUE TITLE
Buyer

### ISSUE THREAD

**Issue by eprocurementontology** [OP-TED/ePO#237]
WG meeting 10/03/2020:
During the WGM everis made a presentation of the Buyer concept. Since updating the organisational model with roles it was deemed necessary to revisit the Buyer model.  Please find the model here: 

https://github.com/eprocurementontology/eprocurementontology/blob/meetings/Presentations/BuyerAndOrganisationExamples.pptx

The Buyer has to be considered as a Role and Organization as an Agent. The Buyer plays the role of an Organization. It allows having Buyer and Organisation as classes with their own related/associated elements.  

Following the discussion, the WG questioned whether the code lists entity-activity and authority-activity were needed for the Buyer. The WG agreed that it is needed to specify which is the main activity of the Buyer. For this purpose, the WG decided to group all the codes in one single code list  named “main-activities”.  Moreover, the WG discussed the activities performed by the buyer are in the context of the Public Sector or Private Sector. To cover both possibilities, the WG decided to have two code lists, one for the main activities (Public Sector) and another one for the other-main-activities (Private Sector). A disjointness between both codes was added since a Buyer cannot have one main activities in Public and Private sectors at the same time. 

It should be noted that the CentralPurchasingBody (CPB)either acts as a buyer or is a buyer in its own right when it is buying for itself.  Therefore there only needs to be a relation between buyer and ProcurementServiceProvider and not with the CPB as the external CPB can use the external service provider via the buyer.

![image](https://user-images.githubusercontent.com/26460487/76620414-61627e80-652d-11ea-9394-8ce17722e587.png)

The discussion is to follow in the next conference call on 17/03/2020 once the working group has reflected on the ideas.

**Comment by JachymHercher** [comment]
1) Are you sure that "a Buyer cannot have one main activities in Public and Private sectors at the same time." What about a contracting entity that is also a contracting authority? In eForms, it is possible, and even required, to have both in some cases. (See Activity Authority (BT-10) and Activity Entity (BT-610) of the Regulation; a slightly outdated overview was in point 4.17 of the [original explanatory note](http://ec.europa.eu/DocsRoom/documents/20224/attachments/1/translations/en/renditions/native)). 

2) "Other-main-activity" would be more precise and more informative as "entity-main-activity", "sectoral-main-activity" or "utilities-main-activity", as it a list of areas where the sectoral directive applies. (Note: there are buyers which do not have any activity, because they are not contracting authorities nor do they not fall under the sectoral directive). 

3) Also, just from a naming perspective, the name "main-activity" might be understood as being more general than "main-activity-other". This could be solved by changing the names to "main-activity-authority" and "main-activity-entity". If the somewhat superficial word "main" was dropped as well, we would get to "activity-authority" and "activity-entity", which would be quite elegant, as it corresponds to the names of the corresponding terms in eForms.

**Comment by eprocurementontology** [comment]
The main activity in version 2.0.1 is associated to the buyer in future evolutions it should be associated to the organisation as forseen in the branch 2.0.2.

**Comment by andreea-pasare** [comment]
In the latest release, ePO 3.0.1, the roles on the buyer side are modeled as depicted in the diagram below:
![image](https://user-images.githubusercontent.com/88081600/203511004-7420be01-d2ad-47a2-8ba0-17162cd9037d.png)
