### ISSUE TITLE
Missing predicate for EconomicOperator?

### ISSUE THREAD

**Issue by guascce** [OP-TED/ePO#239]
I cannot find economicOperator isA Role . May be it is only hidden.

**Comment by eprocurementontology** [comment]
In the diagram Economic Operator you can see the following:

![image](https://user-images.githubusercontent.com/26460487/77909115-0cdd3400-728d-11ea-9b0e-bbc7153c6653.png)

The Role term that appears over the term Economic Operator means that the EO isA Role. This happens when you hide a class that has an inheritance relationship with another class.
