### ISSUE TITLE
CPB can be responsibleOf procedure

### ISSUE THREAD

**Issue by cecileguasch** [OP-TED/ePO#245]
In the current model, this is not possible

**Comment by cecileguasch** [comment]
This has been solved by having CPB as a specialization of Buyer.

**Comment by muricna** [comment]
What about when a cpb is not awarding a contract. The buyer by definition in eforms awards a contract:

•	Definition Regulation (EU) 2019/1780 - Buyer
•	‘Buyer’ refers to a contracting authority, a contracting entity, a defence contractor, an international organisation, or an organisation awarding a contract subsidized by a contracting authority; unless the above mentioned are an association of organisations that is not an organisation in itself, in which case each individual organisation is considered a ‘buyer’

Howevever cpb is not necessarily awarding a contract in situation a of the definition

•	Definition Directive 2014/24/EU Article 2 
‘centralised purchasing activities’ means activities conducted on a permanent basis, in one of the following forms: (a) the acquisition of supplies and/or services intended for contracting authorities, (b) the award of public contracts or the conclusion of framework agreements for works, supplies or services intended for contracting authorities;

Unless a purchase is seen as a contract but if using someone else's contract then they are not in charge of the procedure

**Comment by SellittoGiampaolo** [comment]
well, IMHO a purchase is a contract (if the good has some defect, the buyer or the user can submit a claim ...)
There are at least two parties there: the purchaser (i.e. the buyer) and the seller.
The directive uses purchase as having the same meaning of acquisition ... (see Dynamic Purchasing System)
I think the article 2 is using the  term "purchase" thinking of the DPS as one of the main instruments that the CPB can use.

**Comment by cecileguasch** [comment]
If they use someone else contract (you mean framework agreement?) , wouldn't it be that they are still in charge of the contract based on the framework agreement.?
The distinction made between 'acquisition of supplies/services' and award of public contracts, etc...' is for me related to the fact that acquisition of supplies/services could be purchasing activities where no contract in writing is needed. the definition of public contract:" ‘public contracts’ means contracts for pecuniary interest
concluded in writing between one or more economic
operators and one or more contracting authorities and
having as their object the execution of works, the supply
of products or the provision of services;"

An example of this could be the paper and ink supply in copiers, where the machine informs the need for replenishment and this is enough for launching the acquisition process without concluding a contract each time. 
Other examples are the use of framework agreements that for which they are not buyers.

Proposal: extend the definition of buyer because the case I mention could happen also for  contracting authorities not being CPB that are allowed to use a framework set by another organisation.

**Comment by muricna** [comment]
I would not change the definition as it is written in the regulation, but have nothing against adding something in the additional informaition.
I can understand and agree with what is written above, but the problem I have is when publishing a Contract Notice setting up a Framework agreement for which  lets say Buyer  A is responsible and Buyers B and C are allowed to use the resulting FA to conclude a Purchase Contract.

Can Buyers B and C be considered buyers in the Contract Notice setting up the Framework Agreement as they are not responsible for that procedure?  They are responsible for contracts resulting from that procedure.  Which would mean we need a link also to the purchase order to the buyer and possibly another smaller procedure.  However this does not resolve the question of the CN.

**Comment by SellittoGiampaolo** [comment]
IMHO they are both buyer, since "Buyer" is a role:

If i purchase a pen in a shop, I am the buyer and the shop is the seller,  but the shop in turn is the Buyer when buying the pens from the  wholesale ... and the wholesale is the seller in that case

I see no issue there, as both the CPB and the administrations that use the Framework Agreement have the role of "Buyer", in different procedures (when A and B buy  using the FA, they are involved in another procedure, descending  from the FA)

**Comment by cecileguasch** [comment]
I consider setting up a purchase contract on basis of a FA as a kind of express procedure. Of course this type of procedure is not defined as it does not need the publication of a contract notice. 
From many people I noted that they publish the CAN for those contracts. I wonder how they convey the information.

**Comment by muricna** [comment]
Indeed there is no problem if there are 2 buyers but this is not represented in the ontology in the ontology we have:  
Buyer is responsible for procedure
Procedure specifies Lot
Lot has framework agreement
Framework agreement sets rules for purchase contract

Which does not provide for when the purchase contract is another buyer than the one creating the procedure.

What is more in BT 766 in eForms it states: 
•	Whether a dynamic purchasing system is involved and, in case of central purchasing bodies, whether it can be used by buyers not listed in this notice.
However we are waiting to see from DG GROW whether this should read Contracting authorities  instead of buyers.  If this is the case could we not do the same for Framework Agreements (maybe techniques in general), in which case we would need to add Contracting Authorities to the ontology and we could perhaps have an express procedure going from the buyer to the purchase order.

**Comment by SellittoGiampaolo** [comment]
I'd leave buyer, but let's wait for some input from DG Grow
The CPB is the Contracting Authority, the one that buys the goods in the FA is more properly a buyer, since only orders (yes, an order is a contract as well, but the "contracting" is very limited unless you have a new competition run.

**Comment by paulakeen** [comment]
Indeed we went through this discussion of whether CPB can always be seen as a buyer once again before making the decision of subclassing CPB from Buyer. We also said that it was a pity that @muricna was not able to attend because she would rise the subject of paragraph a) in the Directive once more. But the WG decided that in any case the CPB acts as a Buyer, even in case a) where it could be seen as a co-buyer. In the end, and for practical matters, does paragraph a) actually introduce a significative difference that could lead to roll the WG decision back?

My only concern is that, similary to the decision of making CPB a subclass of Buyer, we could find that the same situation could happen in other circumstances for other roles, e.g.: could a Procurement Service Provider behave as a Buyer? Now, my answer to this tends to be: this could be resolved by using the taxonomy or roles and sub-roles, i.e. A PSP (role) manages (sub-role, activity) the procedure and even executes the payment (if that can happen) on behalf of a Public Organisation.

**Comment by rantati7** [comment]
This may have been commented already and a solution found to the original issue. From the CPB Network point of view, there are two types of CPBs. 

The first type arranges tendering procedure on its own name. CPB is the buyer, signs the contract and orders from the contract on its own name. Of the existing CPBs this is the case amongst the national CPB in France. They operate a warehouse and resell the goods they have ordered from the warehouse to its customers (contracting entities/authorities). In sub-national level the same 'business model' is applied by e.g in Finland Tampere City CPB (name: Tuomi Logistiikka).

The second type of CPBs is more common across EU. In these cases CPB organises the tendering procedure on its own name and signs the contract with its own name. The customers that may use the contract (order from it) are often named or defined by another way in the contract. In these cases the the customer of the CPB place orders to the awarded supplier often directly (without CPB being involved).

One might say that there is a third type of CPB, as well. However I do not see these 'CPBs' as CPBs but rather a procurement service provider. 'The CPB' organises tendering procedures in the name of its customers. In these cases the 'cpb' may be the organisation that receives the bids and co-organises evaluation with the customer under which name it has organised the tendering procedure. The customer, not the cpb, signs the contract. Also, only the customer orders from the contract. 

From tendering procedure point of view I see that there really is only one case: CPB is the buyer (or a subset of the buyer) and also the body that signs the contact.

However, DPS may bring about added complication to this - depending on the country and processes adopted. CPB may set up the DPS (as buyer) and evaluated and allows access to DPS to the suppliers. There may not be a contract or agreement at this stage. Further actions are carried out by the customer of the CPB - also signing contracts without CPBs involvement. In this case CPB may or may not be the buyer (or a subset of buyer).

complicated: definitely YES!!

**Comment by SellittoGiampaolo** [comment]
Yes, definitely complicated... more or less the second case, but here a CPB can award a framework agreement and the other Administrations use the framework agreement signing derived contracts ... they will have a direct customer relation with the supplier, except in the case of litigation, where the CPB will be part again....

**Comment by rantati7** [comment]
Indeed... the same applies to FI.

However, in case of litigations the claims are first and primarly made against to user of the agreement / contract established by a CPB. CPB may have an indirect role in these litigations. The complaining party (often) take s the user of the FA to court. Not necessarily the CPB at all. However the CPB may become party of the litigation later on in the process. Either as an assisting party or as a party having to protect the Agreement / contract established by the cpb earlier on.

Indeed we do assist our customers if they are taken to the court. However, our role is always advisory. The customer is always the one that is taken to the court and I’d unsuccessfully have to pay the cost / rearrange the tendering procedure within FA or a DPS.


----------
Timo Rantanen

Hansel Oy
Mannerheiminaukio 1 A
00100 HELSINKI
Finland
+358 400 838963
timo.rantanen@hansel.fi
________________________________
Lähettäjä: SellittoGiampaolo <notifications@github.com>
Lähetetty: Sunday, September 6, 2020 1:51:02 PM
Vastaanottaja: eprocurementontology/eprocurementontology <eprocurementontology@noreply.github.com>
Kopio: Rantanen Timo <Timo.Rantanen@hansel.fi>; Comment <comment@noreply.github.com>
Aihe: Re: [eprocurementontology/eprocurementontology] CPB can be responsibleOf procedure (#245)


Yes, definitely complicated... more or less the second case, but here a CPB can award a framework agreement and the other Administrations use the framework agreement signing derived contracts ... they will have a direct customer relation with the supplier, except in the case of litigation, where the CPB will be part again....
