### ISSUE TITLE
question on Agent ID

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#249]
In the ontology, is that possible for an Agent to have more than one Identifier (but at least one)? From the UML diagrams is not easy to understand and from the OWL restrictions file it seems not possible. However, an Agent, be it a business or a person or a public organisation may have different IDs according to different systems (IDs of internal systems, or IDs recognised across different databases).

**Comment by paulakeen** [comment]
This is a very old discussion that, unfortunately, could not be resolved appropriately because of the Legislation:

- In the case of the Buyer, there is no obligation in the Directives to provide a unique identifier. Hence, in the current TED forms the identification of the Buyer is done through the name. 
- I have been looking into the [eForms specification](https://simap.ted.europa.eu/eforms) document and [development](https://simap.ted.europa.eu/documents/10184/320101/eForms+schemas+provisional+release+v.+1.1/3a0bff78-7249-4c71-b48c-d75396cfda44) and I see that the Buyer ID is not compulsory, but it is repeatable, 0..n. (unless, further Schematron or other Validation method is implemented that restricts the cardinality on-top-of the XSD Schema, which I cannot find in the deliverables distributed in the above URLs). In the documentation, in section "4.7.4.1 Organisation name and Identifiers", you can find mor hints about this along the sentence "For a given organisation, one or more identifiers issued by a legal authority may be used.".
- Since the OP's UBL customisation is using the UBL Party, the cardinality of the EconomicOperatorParty is the same as for the ContractingParty.

See the _**cac:PartyIdentification**_ aggregate component in the figure below. This is a class, because in UBL there's the 
non-normative rule of not having CBCs (Common Basic Components) with cardinality multiple. Hence its design as a ASBIE (an associated class).
 
![Captura de pantalla 2020-10-20 a las 10 43 50](https://user-images.githubusercontent.com/16134316/96563550-5a210180-12c2-11eb-9606-8475d5be55a1.png)

**Comment by giorgialodi** [comment]
ok, to summarizes, I think that having more than one IDs for Agent is the right solution. BTW: the same approach for identifiers for Person and Organisation is adopted in the SDG sandbox. I would suggest then to revise owl restrictions in this sense too. 

In addition, in the linked data world everything should have an identifier. This does not mean that you must use a property like hasID for the Agent object you are defining. However, it seems quite natural to think that at least one identifier exists anyway :)

**Comment by JachymHercher** [comment]
In eForms, the Organisation Identifier (BT-501) is legally mandatory (and repeatable) for the majority of notices, including all the important ones (for a few notices it stayed optional, because of the restrictions coming from the directives), see https://eur-lex.europa.eu/eli/reg_impl/2019/1780/oj.

**Comment by paulakeen** [comment]
Cardinality of the Agent's Identifier attribute has been changed in v2.0.1 and v2.0.2 to 0..*.
