### ISSUE TITLE
award criterion type

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#265]
With @SellittoGiampaolo we are trying to map the award criterion type used in the Italian context to the related items of the EU controlled vocabulary (https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/award-criterion-type/?target=Browse&uri=http://publications.europa.eu/resource/authority/award-criterion-type)

In the  Italian vocabulary there are some generic items such as "Offerta Economicamente più Vantaggiosa" (the most economically advantageous offer) for which ANAC does not identify the punctual  adopted criterion. 
Is there a way to combine more than one of the codes of the EU vocabulary? that is quality-price or quality-cost ? 

We thought to materialize two values of the controlled vocabulary in case of "the most economically advantageous offer" but we cannot because, as far as I have understood from the ontology an AwardCriterion has maximum 1 award criterion type taken from the EU corresponding controlled vocabulary.

How can we manage this case? /cc @cecileguasch @muricna

**Comment by paulakeen** [comment]
Dear @giorgialodi ,

we are treating this exact topic in the CAV-AC-AP Pilot, where we're using the CAV (Core Assessment Vocabulary, which reuses the CCCEV, the Core Criterion and Evidence Vocabulry) for the eEvaluation of TenderLots.
In this pilot what we do is:

1. We use the AwardCriterion as an extension of the CCCEV Criterion;
2. We instantiate two AwardCriterion to represent two "dimensions": the Quality and the Price. For the evaluation, the Cost is not relevant (Giampalo's explanation for this is that the cost is only relevant for the Economic Operator and is included in the Price. However I am positively convinced, since from my participation in other projects tell me that the Buyer is also interested in knowing the cost to compare it with the quality and the price, thus having sufficient data elements to judge wether the tender is abnormally low or not. We should ask @muricna, @giampaolo, @thor, and other experts).
3. Each dimension usually has its own weight, scoring thresholds (max and min scores), and takes as inputs all the AwardCriteria about that dimension;
4. The MEAT is calculated based on one algorithm specified in the Procurement Documents (e.g. ELECTRE's algorithms and formulae in the case of Italian MEAT. 

As we repeatedly say in the CAV and CCCEV WG meetings, the criteria should be agnostic of how it is evaluated, and therefore it would be for the eEvaluation phase to decide, based on the CAV Scenario and EvaluationContext classes to specify whether to evaluate the Tender Lots based on MEAT or no. 

Nonetheless, this has to be "announced" in the PIN and CN, and therefore we need a placeholder for this. But I don't think that placeholder is the AwardCriterion Type.

**Comment by giorgialodi** [comment]
Hmmm, I am not sure to have completely understood the point. BTW: are you defining an application profile with instances of data? Probably I miss the other context. In any case, looking at our data I do not think we can do two instances of the award criterion. It seems to me that complicate stuff in an unnecessary manner.

I see two possible "quite easy" solutions:
1) If we maintain the current controlled vocabulary on Award Criterion Type, in epo, the cardinality of the property hasAwardCriterionType can be 0..N instead of 0..1 as it is now. This would preliminary solve our current issue;
2) we investigate the possibility to extend the controlled vocabulary in order to take into account these situations. In this case, there is no need to change the cardinality of the hasAwardCriterionType property of epo. This solution is wider than the first one. 

I think we should discuss about all the issues in Github in the working group too.

**Comment by giorgialodi** [comment]
After the discussion with the WG we discovered that the it it likely that the mapping we were trying to do with @SellittoGiampaolo does not regard the award criterion type but the method of the evaluation that, at the time being, is not part of epo ontology. See also https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32014L0024&from=EN (point (89)). 
Therefore the current decision is not to consider that data of the original dataset from ANAC in the mapping for the BDTI pilot.
