### ISSUE TITLE
Buyer definition does not cater for post award needs

### ISSUE THREAD

**Issue by cecileguasch** [OP-TED/ePO#279]
In a post award context, the Buyer will purchase on basis of an already awarded contract. The definition should mention this alternative

**Comment by idolum** [comment]
As additional information:

Definitions used by Peppol:

* Buyer (Business Role): Is the legal person or organization acting on behalf of the customer and who buys or purchases the goods or services.

Definitions used by UBL:
* Buyer: The Party Role for a Party that purchases the goods or services on behalf of the Originator.
* Originator: The Party Role for a Party that had the original demand for the goods and/or services and therefore initiated the procurement transaction.

**Comment by eprocurementontology** [comment]
Regulation (EU) 2019/1780 defines a Buyer as follows: Contracting authority, contracting entity, a defence contractor, an international organisation, or an organisation awarding a contract subsidized by a contracting authority.
Hence EU vocabularies uses the same definition.
To cover the post-award needs and some other pre-award needs we could add comments in the additional information to provide for other needs.
The problem with the definition is it states "awarding a contract" when in fact a buyer purchases the object of the procurement.
Furthermore the use of the term subsidized does not seem to fit as our understanding is that subsidized means providing financial support and not the payment as procurement.
The definition would not appear to fit with the eInvoicing norm.
The issue should be brought to the attention of DG GROW.
It is not clear whether the work around could also be applied to the controlled vocabulary.

**Comment by JachymHercher** [comment]
> The problem with the definition is it states "awarding a contract" when in fact a buyer purchases the object of the procurement.

This part of the buyer definition comes quite directly from Art. 13 of Directive 2014/24/EU. 

Concerning the general point on "awarding a contract" vs. "purchasing the object of the procurement", the procurement Directives speak mainly about public contracts, so eForms approach things similarly.

**Comment by eprocurementontology** [comment]
Thank you for this clarification it would seem that rather than being a definition of what a buyer is  the list:

- contracting authority _(Directive 2014/24/EU)_, 
- contracting entity _(Directive 2014/25/EU)_
-  a defence contractor _(Directive 2009/81/EC_),
-  an international organisation _(Directive 2014/24/EU Article 9b)_,
-  or an organisation awarding a contract subsidized by a contracting authority (_Directive 2014/24/EU Article 13)._

provides the examples of buyers within the procurement directives (see limited examples above).

**Comment by JachymHercher** [comment]
Well, within the procurement directives (/eForms), it is an exhaustive list rather than examples. Defining a concept through such a list has the advantage of being able to rely on concepts that are defined elsewhere (often in huge detail, e.g. there is a ton of case-law on what a contracting authority is and isn't). The fact that some things are excluded from being a buyer is a feature in this sense, not a bug - eForms sees things the same way as the Directives. 

Whether this fits for the ontology depends on the ontology's users / use cases I guess, but assuming that the ontology needs to be alinged with eForms, then I'd think there wouldn't be much scope for narrowing nor expanding the definition.

What are the organizations that you'd like to be covered by buyer, but they are not? For example, most organizations buying on the basis of an already awarded contract will still be contracting authorities, so they should be within the definition's scope.

**Comment by andreea-pasare** [comment]
As of ePO version 3.0.1, the definition for `epo:Buyer` is:

_A role of an agent that awards a contract and/or purchases items._

_Additional information: 
In public procurement the role of buyer is carried out by the following types of organisation contracting authority, contracting entity, a defence contractor, an international organisation, or an organisation awarding a contract subsidized by a contracting authority. 
In pre-award, the buyer generally awards the contract, however future purchasers may be foreseen. 
In post-award the buyer generally refers to the purchaser of items._
