### ISSUE TITLE
Quantity class and its mandatory properties

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#280]
In the Quantity class the hasQuantityValue property is mandatory but it is also madatory hasUnitCode that should use a controlled vocabulary.

I do not think it is wise to keep hasUnitCode mandatory. Which is the associated controlled vocabulary? Measurement Unit of the EU vocs is not always appropriate for that property. For instance in soem data I saw hasTotalMagnitudeQuantity Quantity referring to buses that is not in any controlled list.

So, I would relax that constraint for hasUnitCode.

**Comment by paulakeen** [comment]
Agree: 1) the hasQuantityValue has to be mandatory since otherwise it makes no sense to use the class at all; and 2) the hasUnitCode must not be mandatory (should become 0..1). 

This was discussed in at least one WG Meeting where it was said that the Units, as well as the Measures, vary extremely depending on the domain. Thus, in eHealth procurement one can find thousands of different types of units and measures that would be totally different to the ones used for procurement of Public Works, ICT, etc.

Each Sector or even Use Case needs its own Unit and Measures code list (or taxonomies).

**Comment by ec-mcs** [comment]
I am not sure how hasUnitCode is defined. Is there a codelist on units? If not, I would suggest to create this codelist. There are indeed different types of units and measures but it is important to understand what type of unit it is.

**Comment by muricna** [comment]
In the version of the model that was released on 19 March there is no code list associated to the class, there is a unit description.  The EU vocabularies code list measurement-unit is associated to the measure class.
