### ISSUE TITLE
Economic Operator class: EORoleType property

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/ePO#282]
In the class Economic Operator there is a property that is mandatory hasEORoleType. In particular it can assume at least 1 value from a controlled vocabulary that is espd role type. 

How come that the property is 1..* but the vocabulary consists in 1 concept only? 

Can we:
1) relax the cardinality
2) revise the content of the vocabulary (probably it should have more than 1 value if the cardinality is 1..*)
3) specify the complete URI of the controlled vocabulary. Where can we locate it?

Thanks a lot!

**Comment by paulakeen** [comment]
This codelist was inspired by the one used in ESPD, where the roles were originally Consoritum Leader (we transformed this into Lead Entity), Sole Contractor, Other Entity (relied-upon and non-relied-upon), and Group Member (for the members of Consortia that are not Leads. Note that these roles are mutually exclusive!

Agree that the cardinality should be relaxed to 0..1: I do not see how an Economic Operator can play two of these specific roles at the same time. In case the codelist was extended with other roles that are not mutually exclusive, the reification would probably show that it would link different "Things" to the same Economic Operator and to one particular role or other; in which case we would have multiple instances of the reification class.

**Comment by ec-mcs** [comment]
I am not sure if I understand this discussion. In a public procurement procedure an EO has a specific role. As in the ESPD it is mandatory (to my knowledge), why should it be different in the ontology?

**Comment by SellittoGiampaolo** [comment]
The real issue here is how we use the ontology and which is the underlying assumption (closed world CWA or open world OWA, as discussed in Luxembourg more than one year ago). 
At this point, with the big ontology, it is difficult to draw the cardinalities just looking at the most likely examples.
A solution  would be to factor the ontology in small pieces, each one describing a use case with its own compentency question. In this manner, the data would respond to a specific question, describing a piece of the world and the cardinalities will come as a consequence.  Picking the ESPD as an example, we would derive cardinalities from the ESPD requirements and one of the two assumptions. But the cardinalities would be specific of the ESPD, and again they would depend on the assumption.
With OWA the cardinality can be 1..1 as we know that in a specific ESPD the EO can have just one role and even if this role is unknown in the instances, it is known in the world and at some point we will know it.
Different is the case when we look at different instances of the ESPD since there the EO can have different roles and cardinalites are 1..n if we intend that as a data model (an ontology is not a data model, actually, but when you impose shapes it becomes something similar to a data model). 
With CWA we must be even more elastic, since the piece of ontology becomes a data model and if implemented, we must cater for the case of the EO registration when the role is unknown or again, with the possibility that the EO plays multiple roles in different contexts.

The result is that it is really difficult to define cardinalities in an abstract way, since they dipend on the use case and on the usage foreseen for the resulting ontology.

**Comment by paulakeen** [comment]
I tend to agree with @SellittoGiampaolo, yes...more Use Cases would be needed.

**Comment by giorgialodi** [comment]
I try to explain better the point here. In the current version 2.0.1 of the ontology the controlled vocabulary epo:espd-role-type includes JUST ONE value; that is, "Other entity (relied upon)". However, the current cardinality for the property that links an Economic Operator to this controlled vocabulary is 1..* and it does not make sense, independently of the fact it is mandatory or not.

Reading this conversation I would suggest acting in the following way:

1) revise the controlled vocabulary and make it available as a semantic web resource, if it is not already available in the list of EU vocabularies, including the other roles that have been mentioned in this thread and that apparently are not there
2) relax the cardinality in the ontology so that the ontology can accommodate different use cases. 
3) if an economic operator can assume just ONE role at a time, then it should be 0..1
4) with the reification we introduced in successive versions of the ontology, it is likely that this thing may be different and we need to verify that everything works fine.

I personally do not consider ePO a core vocabulary fully open world.  From my point of view, it is the European application profile for the e-procurement, even if we relaxed many constraints recently when we revised the cardinalities. With this application profile, others can be crated according to the different use cases.

my2cents

**Comment by eprocurementontology** [comment]
The code list to be used in the future is [eo-role-type](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/eo-role-type)

This controlled vocabulary has 4 values

The cardinality should be looked into especially when applying the reification.

**Comment by andreea-pasare** [comment]
This code list have been retired since all the roles contained within the list are already coverd by the latest ePO release, 3.0.1.
