### ISSUE TITLE
where are the xslt?

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#286]
Hi Everis! @eprocurementontology @Ana-MariaBabaligea @mfontsan @mfontsan @jseguraf 

I'm looking for some XSL or XQuery to transform `TED_EXPORT` to tabular form.
RDF would also do since I can SPARQL out of it.

https://eprocurement-everis.github.io/#technical-approach says that an `xslt` is available, but I can't find it.
Or do you know of any site that has current TED contract award notices?

**Comment by eprocurementontology** [comment]
Hello,

Thank you for your interest and sorry for the delay in replying.

The xslt you mention is related to an old version of the ontology and we do not recommend its use as there have been many changes since.

We are currently working on providing rdf files of the TED data  and will be making it available at a later date.

You may be interested in the subset of data produced by DG GROW which is available in CSV format at: https://data.europa.eu/data/datasets/ted-csv?locale=en

Should you require any further information or would like to join our working group on building the ontology please let us know.

**Comment by VladimirAlexiev** [comment]
@eprocurementontology thanks for TED-CSV , I easily found what I was looking for, and it matches TED XML download results. but it's missing years 2020 and 2021...

I'd like to join the WG , though I don't know how much time I can devote to it.  I posted some issues at https://github.com/OP-TED/model2owl/issues/. Cheers!

**Comment by VladimirAlexiev** [comment]
Closing for now, and looking forward to
>providing rdf files of the TED data

**Comment by VladimirAlexiev** [comment]
I just checked: https://data.europa.eu/data/datasets/ted-csv?locale=en is `Updated	11.02.2022` and has up to and including 2020. This is one extra year, so I guess it takes OPOCE more than 11 months to publish a yearly run of the TED notices :-(
