### ISSUE TITLE
avoid unspecific properties

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#297]
The worst offender is `epo:has` (ePO_restrictions.ttl release 2.0.1):
```ttl
epo:has  a           owl:FunctionalProperty ;
        rdfs:domain  [ a            owl:Class ;
                       owl:unionOf  ( epo:PlannedProcurementPart epo:Address epo:AwardDecision epo:Buyer epo:ContactPoint epo:Role epo:Procedure epo:EvaluationBoard epo:Lot )
                     ] ;
        rdfs:range   [ a            owl:Class ;
                       owl:unionOf  ( epo:AccessTerm epo:LocationCoordinate epo:Winner epo:BuyerProfile epo:Channel epo:ContactPoint epo:ContractTerm epo:DirectAwardTerm epo:ExclusionGround epo:Purpose epo:OpeningTerm epo:ProcedureTerm epo:Subcontract )
                     ] .
```
Not surprisingly, there is no definition of this prop.
You could add definition "A quality, part or characteristic of this resource" but it's quite unspecific

https://github.com/OP-TED/model2owl/issues/91 complains about being unable to tell which domain class pairs with which range class.

But I looked in the UML documentation and I know one of the pairs is:
`epo:EvaluationBoard epo:has epo:ExclusionGround`.

But I still can't figure out:
- how can a Board have an ExclusionGround? Aren't ExclusionGrounds applied on tenders and lots?
- is it true that there can be only one ExclusionGround per EvaluationBoard (stated by owl:FunctionalProperty)? Aren't ExclusionGrounds various and sundry, and several of them can apply to the same case?

If there was a specific prop between `epo:EvaluationBoard` and `epo:ExclusionGround`, these questions could be answered by the ontology.

BTW, *Is it true that epo:has is a owl:FunctionalProperty*?

**Comment by giorgialodi** [comment]
Please see also comments in issue #281, where this specific property is mentioned :) In the current revisions, not yet published, this property will be changed.

**Comment by VladimirAlexiev** [comment]
@giorgialodi Is it true that epo:has is a owl:FunctionalProperty?
It seems to me that at least the use of epo:has  for ExclusionGround should be multi-valued.

**Comment by giorgialodi** [comment]
@VladimirAlexiev it seems so looking at the OWL file of the version 2.0.1 but I do not think it is correct.  Here there are two points to highlight IMHO: 1) "has" is no longer available in the new version we are working on; we decided to revise all those properties that are applied to many domains and ranges and that can cause semantic inconsistencies and also, let me say, not clear semantics; 2) the definition of functional properties, (a)symmetric ones and also of the disjointedness axioms are to be revised: after some checks in the working group we noticed that there are some of these axioms that are not correct and this might be (we are not sure and we need to further investigate it) derived from some conventions adopted in the automatic translation from UML to OWL. The point is that I personally notice that automatic translation is cool from one side but adjustments are required in any case since UML is not that expressive as it is OWL and some things are not subject to a general rule: it depends on what we model. This consideration, from my personal point of view, might be applied to the functional axiom for "has" in the specific case you mention.

**Comment by guascce** [comment]
As Giorgia rightly mentions we took care of revising all the predicates that were creating ambiguity. 
We still need to refactor the code that produces the OWL from UML an d that controls the definition of specific axioms like FunctionalProperty. Cardinalities can help us define whether it would be Functionalproperty or not. This will be dealt in the next release.

**Comment by andreea-pasare** [comment]
This has been fixed. In the latest release, ePO 3.0.1, all properties are well scoped.
