### ISSUE TITLE
Implement mapping of the competition notices content to situations

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ePO#334]
The mapping of the competition notes content to situations is implemented in the following branch:
https://github.com/OP-TED/ePO/tree/feature/model-refactoring

**Comment by giorgialodi** [comment]
Hi @andreea-pasare this link brings to 404 error.

**Comment by costezki** [comment]
The notice content mapping will be done in the future release. It is of lower priority for the moment.

**Comment by AchillesDougalis** [comment]
It was decided that we will not model situations in ePO at the moment.

**Comment by muricna** [comment]
Please ensure the link works

**Comment by AchillesDougalis** [comment]
The branch was already deleted since we do not plan to implement situations, and that is why the link is not working.  For more information on  work done regarding situations in ePO please consult the ePO WG meetings from [1/2/2022](https://docs.ted.europa.eu/epo-wgm/wgm-2022.html#_working_group_meeting_01022022) to  [17/5/2022](https://docs.ted.europa.eu/epo-wgm/wgm-2022.html#_working_group_meeting_17052022)
