### ISSUE TITLE
Roles classification

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#388]
type 1: buyer-side, supplier-side, third party
type 2: primary, secondary  (tertiary)

Shall we use type 1, type 2, or both classifications? 
Recommended: keep only one (not two); keep type 1. 

![image](https://user-images.githubusercontent.com/13567133/198999396-2d7686d7-e93f-45f2-90c7-c1ddd6cced2b.png)

![image](https://user-images.githubusercontent.com/13567133/198999276-874026a6-5c19-48fa-9628-b9a97ac90b81.png)

**Comment by giorgialodi** [comment]
The word "Party" makes me think to an agent rather than a role. So I would answer: use the second one, but if this distinction is really necessary :)

**Comment by costezki** [comment]
The following definitions have been proposed. 

**AquiringParty**

> The role of an agent that acts on the buying side of a procurement process.

**OfferingParty**

> The role of an agent that acts on the economic operator side during a procurement process.
> 
> Additional information:
> As per the European Procurement Directives the notion of ‘economic operators’ should be interpreted in a broad manner so as to include any persons and/or entities which offer the execution of works, the supply of products or the provision of services on the market, irrespective of the legal form under which they have chosen to operate. Thus, firms, branches, subsidiaries, partnerships, cooperative societies, limited companies, universities, public or private, and other forms of entities than natural persons should all fall within the notion of economic operator, whether or not they are ‘legal persons’ in all circumstances.

**AuxiliaryParty**

> Role of an agent who may be mentioned in the information exchanged during the procurement process but who does not play an active part in it.


![image](https://user-images.githubusercontent.com/13567133/200019882-b44a4874-3622-4116-8502-fd34548dcfb3.png)

**Comment by giorgialodi** [comment]
I still think there is a confusion in the terminology between the Agent concept and the Role concept. If you look at DUL, Role is a Concept not an Agent and party is defined among the others: a person or people forming one side in an agreement or dispute, so it seems more an Agent rather than a role. 
But since AgentInRole is a real agent (in a specific role) probably overall sounds coherent. 
BTW: I see that AgentInRole is a dul:SocialObject. But since in DUL Role is a Concept (subclass of dul:SocialObject) and the concept of Agent of AgentInRole is probably represented by dul:Social Agent (subclass of dul:SocialObject) and Concept and Social Agent are disjoint, I am not quite sure in general. 
But never mind, probably it is my bias of modelling the role according to different patterns.
