### ISSUE TITLE
Modification notice model in Standard forms

### ISSUE THREAD

**Issue by costezki** [OP-TED/ePO#389]
To be discussed in the EPO WG meeting.

![image](https://user-images.githubusercontent.com/13567133/199214637-f36b7c1c-89c8-4622-a2b8-039d8b8291bb.png)

![image](https://user-images.githubusercontent.com/13567133/199214690-effae32f-cf39-4136-9039-9852a1ba7e89.png)

![image](https://user-images.githubusercontent.com/13567133/199217291-2281d893-d521-43e4-98a7-26df1b958a05.png)

![image](https://user-images.githubusercontent.com/13567133/199217675-e8f3fcd7-2c95-4537-aca6-fedccb4cb924.png)

**Comment by andreea-pasare** [comment]
The epo:containsModificationsOn relation has been added on the epo:AgentInRole class since epo:Winner can be also modified in Modification Notice.
![image](https://user-images.githubusercontent.com/88081600/199499745-f98e36cc-1de4-4cd3-b1fd-0d021a0c3c3f.png)

**Comment by giorgialodi** [comment]
What does it mean that an AgentInRole containsModificationsOn an AgentInRole? Do you mean changedIn? Or do you mean that there is a general relation between AgentInRole instances?

**Comment by costezki** [comment]
That relation was introduced when more fundamental work was done, but we do not seem to need it anymore, so it was removed.

**Comment by costezki** [comment]
It seems that we need to further discuss this matter. 
The solution of using RDF reification to express modifications might be a better alternative to the current proposed solution. 

@giorgialodi it was meant to say that an instance of an object can be modified by another instance of an object of the same type (the latter contains only properties with the new values and is meant to override the forme one).

**Comment by muricna** [comment]
A modification notice concerns a modification to the contract ie the change of name of an economic operator I think therefore the modification needs to be made at Agent level.  We need to look closely at the use cases

**Comment by giorgialodi** [comment]
But do you change the name of the agent playing the role of the economic operator? Do you change the role from economic operator to something else? BTW: I think @muricna that you are writing about a modification of the contract, not of the agent. 
In any case, AgentInRole containsModificationsOn AgentInRole sounds very weird to me: what does it mean contains? Probably the modification notice contains the indication that there is a modification of the contract.

**Comment by giorgialodi** [comment]
@costezki difficult to follow. Do you have an example of instances of AgentInRole class that are to be modified by other instances of the AgentInRole?

**Comment by costezki** [comment]
Yes, we have examples.
This is best discussed in the EPO WG meeting. @giorgialodi, your input would be valuable and highly appreciated.

**Comment by giorgialodi** [comment]
@costezki I need to find the time among all my current activities. I will see if I can participate in the meeting next Tuesday!

**Comment by muricna** [comment]
> But do you change the name of the agent playing the role of the economic operator? Do you change the role from economic operator to something else? BTW: I think @muricna that you are writing about a modification of the contract, not of the agent. In any case, AgentInRole containsModificationsOn AgentInRole sounds very weird to me: what does it mean contains? Probably the modification notice contains the indication that there is a modification of the contract.

@giorgialodi yes the modification of a contract could be that the name of the agent changes not the agent itself that is why I said we need to look at the use cases and we need to look at if the predicate is appropriate.

Have a nice weekend everyone.

**Comment by costezki** [comment]
After some more internal debates, we decided to relax the Domain and Range of the `epo:containsModificationsOn` to "Anything" like in the following diagram.

![image](https://user-images.githubusercontent.com/13567133/200327567-5334b1ea-dedd-4fed-8a9a-570fa5660918.png)

**Comment by csnyulas** [comment]
I wish I was involved in the latest discussions regarding this problem, as it was @andreea-pasare and myself who came up with the solution of adding the relationship `epo:AgentInRole epo:containsModificationOn epo:AgentInRole`, in order to be able to represent the the modifications on the winner of a contract that can be expressed in section VII.1.7 of standard form F20.

The first part of the solution described in this issue by @costezki, where we suggested to add `epo:ProcurementElement epo:containsModificationOn epo:ProcurementElement`, allows us to represent nicely modifications on Procedure, Lot and Contract, which are described in sections VII.1.1 through VII.1.6
![image](https://user-images.githubusercontent.com/2441046/200397459-ae4dc759-fb89-4c2c-84ce-58961b01daf1.png)

However to represent the modifications to the winner of the contract, described in section VII.1.7 (see below), we needed to add the `epo:containsModificationOn` relation to the `epo:Winner`. We thought that it would be even better to add it to any `epo:AgentInRole`, not just the `epo:Winner`, in case some other forms (which we didn't map yet or might be created in the future) will allow the modification of information on some agents playing a different role. (**Side note:** Making it totally generic, as per the last suggestion, to be `owl:Thing epo:containsModificationOn owl:Thing`, opens up its interpretation way too much, in my opinion, and looses its intended meaning. Naturally, the `epo:containsModificationOn` property should be defined to represent some relationship between some EPO classes, not on any imaginable thing in the world.)

![image](https://user-images.githubusercontent.com/2441046/200378115-eadbd29d-b4f5-4fa6-9973-b9ed3229a098.png)

The key reasons for which we found that the best approach to represent the modifications that can happen on the "contractor/concessionaire" information is to add the `epo:containsModificationOn` property to the `epo:Winner` (or more generically its superclass `epo:AgentInRole`) is that according to the standard form F20 (and its associated XSD), any aspect of the contractor can change. Not merely its official name, (parts of) its address, or whether it is an SME or not, but theoretically a contractor can be replaced with a different contractor, or a group of contractors, and vice versa. Or the members that formed the group of contractors in the original notice can change (by adding removing contractors).
So, the best way that we found to represent this, is to create a new `epo:Winner` instance, played by the agent described in section VII.1.7 ( which can be a single Organisation or a Group of Organisations), that has a relationship `epo:containsModificationOn` to the `epo:Winner` instance that was created from the sections V.2.2 and V.2.3.

**Comment by giorgialodi** [comment]
I think it is a long discussion here and probably also the role managed in this way opens up these issues. What is changed is not the agent it is the contract that indicates a different agent in the role of winner, as far as I have understood from @muricna. So probably managing roles in a different way with a time interval (if this data is available)l too allows you to better represent these situations. There is a new situation here, given by a modification of the contract, that says that Agent 1 with role winner is no longer valid and now it is Agent 2 in the role of winner. The winner role is always the same, the agent is always the agent, what changes is the situation connected with the new contract instance for which the role of winner is now played by Agent 2. I agree with @csnyulas that the property, whose name should be carefully analysed IMHO, from owl:Thing to owl:Thing is too vague and probably should be avoided to be better focused on the specific cases of the domain. 
Today I have an overlapping meeting but I can try to join you later on in usual ePO afternoon meeting.

**Comment by costezki** [comment]
After a discussion in the WG, it was concluded that the modifications are on the `epo:Contract`, not any other ProcurementObject. The `Contract` module of EPO is not yet completely modelled, and therefore modifications implementation should be addressed as part of the modelling Contract module.

**Comment by andreea-pasare** [comment]
In ePO v4.0.0-rc.1, the modification of a Contract is covered by a Contract Amendment, which is a type of Contract.
![image](https://github.com/OP-TED/ePO/assets/88081600/e3ad23a5-a351-4e3a-b0eb-daf6b7cb816e)

The modifications of the Contract are represented in a Modification Notice as follows:
![image](https://github.com/OP-TED/ePO/assets/88081600/9e94b9ba-4d06-4873-998b-858e498c79f6)
