### ISSUE TITLE
Is bound to - Relationship

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#4]
The relationship is difficult to understand

**Comment by makxdekkers** [comment]
The current definition is confusing. A better definition could be: "this property links a Contracting Agency or an Economic Operator to a Contract they have signed".

**Comment by muricna** [comment]
This is much clearer, however you have introduced a new term: Contracting Agency - we really need to clear up the situation on Contracting body, buyer, Contratcing authority, Contracting entity  etc

**Comment by makxdekkers** [comment]
Apologies, sloppy drafting on my part. I wanted to write Authority not Agency. But indeed we need to agree the class name.

**Comment by JachymHercher** [comment]
Can't this relationship be replaced by "signed"? 

With a definition of "An actor has signed a document", or something similar?

**Comment by makxdekkers** [comment]
In the latest version of the conceptual model (to be provided ahead of the WG meeting of 24 May 2017), this relationship has been replaced by relationships of Contract, ‘is contracted by’ a Buyer and ‘is contracted to’ and Economic Operator.

**Comment by JachymHercher** [comment]
Why not "signed" - please see comment above?

I'm guessing you might have wanted to emphasize the direction of the contract (by/to). I would say this is not necessary, because the information on the direction can always be found by linking the data with other data. Specifically, if I see that a buyer and an economic operator have both signed a contract, then I can figure out who was buying and who was selling on the basis of who they are. It does not need to be repeated by having relationships "is contracted by" / "is contracted to". 

Having only one relationship for both is definitely more parsimonious (something we should strive for in an ontology) and I would argue also more correct because it reflects the fact that the role of both parties is exactly the same. They are bound by what is written in a contract because they have signed a contract.

**Comment by muricna** [comment]
I would tend to agree but maybe there is a subtilality that we are ignoring

**Comment by ocorcho** [comment]
I also agree that the usage of "by" and "to" is probably not so necessary, given that the different targets of the property will tell whether it is a "by" or a "to". It is a question of understanding the role of the entity in signing

**Comment by brechtwyns** [comment]
Agreed resolution in the third Working Group:

**The relationship should be "signed by"**. There is no need to distinguish "signed by" and "signed to".

**Comment by noeclai** [comment]
Then please, write **'signed**" only and not **'signed by'**

**Comment by makxdekkers** [comment]
I think:

- Contract "is signed by" Organization 

is clearer than:

- Contract "signed" Organization

**Comment by noeclai** [comment]
Agree, of course,

**Comment by JachymHercher** [comment]
Yes, but the inverted relationship does work with "signed". Is there some reason to use the passive form instead of the active?
* Organisation "signed" Contract.

**Comment by makxdekkers** [comment]
Yes, the inverse works with "signed". The reason to use "isSignedBy" as a property of a Contract rather than "signed" as a property of an Agent is because we try to assign the property to the entity where it is more easily managed in instance data. In this particular case, it is easier to manage the links to the contract partners in the metadata for a contract as the partners are fixed at the time the contract is signed. If, on the other hand, a link to a contract was included in the metadata for the buyer, you would need to update the metadata for the buyer every time that organisation entered into a contract.

**Comment by JachymHercher** [comment]
I'm sorry, I don't have much previous experience with ontologies, so I don't quite understand. 

1) What do you mean by property?  I thought "signed" is a relationship (with a domain that includes buyer and a range which includes a contract), not a property? 
2) I don't quite understand the instances math. Aren't we in both cases just adding contract classes and signed/isSignedBy relationships?

**Comment by makxdekkers** [comment]
1. My apologies. I am sometimes using the terms loosely which may be confusing. In RDF, there are only classes and properties. RDF properties may have a range of rdf:Literal (e.g. dates, text, integers) or a range of things that are identified by URIs. OWL makes a distinction between the two: properties with literal values are called data properties and properties with URI references are called object properties. We sometime refer to OWL object properties as relationships but they are just properties for RDF. So "signed" is a relationship which is an RDF property with a 'thing' as it range (Contract); for OWL it's an object property.
2. Yes, from a modelling perspective "Buyer signed Contract" is completely equivalent with "Contract isSignedBy Buyer". The issue is whether to declare both or only one of them. The choice I made was to declare the relationship on the class where it would be more efficient to manage in the instance data, i.e. when creating metadata for actual contracts, it would be more efficient to point to the contract partners from the contract rather than from the contract partners to the contract.

**Comment by JachymHercher** [comment]
1. Great, thanks, now I understand.
2. "Efficient" in what sense? Is e.g. "readability" part of the decision - i.e. it's probably easier to have contracts, each with meta-data about two parties; rather than various parties, each with meta-data about "hundreds" of contracts?

**Comment by makxdekkers** [comment]
2. Efficient with respect to the implementation of the model. Indeed, it's easier to manage the links to partners in the metadata for a contract than to link an organisation to all the contracts it signs.

**Comment by JachymHercher** [comment]
2. Could you be more concrete than "with respect to the implementation of the model"? For example, I'm thinking that a common question asked of the data may be "How many contracts did buyer A award over period X?". Is one of the options above easier from the point of finding the data which answers this question, or are they the same?

(Sorry for going into the nitty-gritty, I'm thinking it may be useful to understand this 100% also for other similar situations that may arise.)

**Comment by makxdekkers** [comment]
I was referring to implementation as related to data management, in the sense of minimising the effort to keep the data up-to-date. From a perspective of data usage and search, I don't think there is much difference: you can write SPARQL queries in both cases that come up with the answer.
