### ISSUE TITLE
change `rdfs:Literal` to `rdf:PlainLiteral`

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/ePO#405]
You use `rdfs:Literal` for string fields. However, that datatype is overly wide. You won't be happy about a company name having values like:
- `"2022-11-06"^^xsd:date`
- `"POINT(10 20)"^^geo:wktLiteral`
- or even `"<html><title>foo bar</title></html>"^^rdf:XMLLiteral`

Please use `rdf:PlainLiteral` instead, which in effect is a union of `xsd:string` and `rdf:langString`. 
See the spec: https://www.w3.org/TR/rdf-plain-literal/

**Comment by AchillesDougalis** [comment]
In the [glossary ](https://docs.ted.europa.eu/EPO/latest/_attachments/html_reports/glossary/ePO_combined_glossary.html) of ePO 4.0.0 there are only `rdf:PlainLiteral` and not `rdfs:Literal`.

**Comment by VladimirAlexiev** [comment]
https://github.com/search?q=org%3AOP-TED+rdfs%3ALiteral&type=code shows 30 occurrences of `rdfs:Literal`:
- in model2owl configurations (cc @costezki )
- in SHACL shapes, eg `epo:hasShippingMark, epo:concernsBeneficiary, foaf:name`

Commits that make such a change:
- https://github.com/OP-TED/ePO/commit/5052225b35c3c555ed314e33a6038b81c4d678b9 modifies analysis_and_design/conceptual_model/ePO_CM.eap  but I don't know what is its effect
- https://github.com/OP-TED/ePO/commit/65b01ac5fe282d0c82feaab278c9b8cfefe78d9c is a hotfix to just one field.

@AchillesDougalis , you trust that Glossary too much! Please reopen.
- Note: https://github.com/OP-TED/ePO/issues/447 is a duplicate, closed for a different reason (imho also invalid)

**Comment by andreea-pasare** [comment]
@VladimirAlexiev, indeed, we do have some occurrences of `rdfs:Literal` in all OP-TED repositories, and in ePO we only have it mentioned in the model2owl-config folders, in config-parameters.xsl files (https://github.com/search?q=repo%3AOP-TED%2FePO++rdfs%3ALiteral&type=code). Those are variables that are not used anymore by model2owl when generating the RDF outputs for ePO. 

We do want to have a proper clean-up of the entire model2owl configuration files in the ePO repository in a future release and it will be tracked in a separate discussion: https://github.com/OP-TED/ePO/discussions/588 (from which we will create an appropriate github issue once we get started). So thank you for this feedback, I will make sure to add it in our discussion.

Regarding the other issue (https://github.com/OP-TED/ePO/issues/447) it was converted into a discussion, but in my opinion we should also close that since it became a discussion about a different repository (https://github.com/OP-TED/ted-rdf-mapping) and an appropriate issue to track it was created: https://github.com/OP-TED/ted-rdf-mapping/issues/407.

**Comment by VladimirAlexiev** [comment]
@andreea-pasare 
> in ePO we only have it mentioned in the model2owl-config folder

That's not true, there are numerous semantic files with this defect. Here are the number of occurrences:
- 16 src/validation/shacl/epo/eCatalogue_shacl_shapes.ttl
- 99 src/validation/shacl/epo/ePO_shacl_shapes.ttl
- 1 src/validation/shacl/epo/eOrdering_shacl_shapes.ttl
- 86 test/reasoning-investigation/model-2020-12-16/epo-restrictions(-[124])?.ttl

There are also numerous occurrences in EA.html files, i.e. directly in the UML models (cc @costezki).

I'm happy if this will be addressed in https://github.com/OP-TED/ted-rdf-mapping/issues/407

**Comment by andreea-pasare** [comment]
@VladimirAlexiev, the files mentioned above are not part of the [ePO repository](https://github.com/OP-TED/ePO) and:

- the files having `src/validation/shacl/epo` path come from [ted-rdf-mapping project](https://github.com/OP-TED/ted-rdf-mapping/tree/main/src/validation/shacl/epo) where they have old ePO files that were used for validation purposes (last commit being last year), 
- while the last path `test/reasoning-investigation/model-2020-12-16/` is from a test folder of [model2owl project](https://github.com/OP-TED/model2owl/tree/master/test/reasoning-investigation/model-2020-12-16) (last commit being 3 years ago).

Thank you for catching this :) Both of those projects would benefit from having general "clean-up repository" tickets as we have in ePO, so I will make sure to sync with them on this topic.

**Comment by VladimirAlexiev** [comment]
Thanks for the clarification! For the record, here are the occurrences of `rdf:PlainLiteral`:
-   1 implementation/eCatalogue/owl_ontology/eCatalogue.ttl
-  11 implementation/eCatalogue/owl_ontology/eCatalogue_restrictions.ttl
-  14 implementation/eCatalogue/shacl_shapes/eCatalogue_shapes.ttl
-   1 implementation/eContract/owl_ontology/eContract.ttl
-   2 implementation/eContract/owl_ontology/eContract_restrictions.ttl
-   2 implementation/eContract/shacl_shapes/eContract_shapes.ttl
-   1 implementation/eFulfilment/owl_ontology/eFulfilment.ttl
-  10 implementation/eFulfilment/owl_ontology/eFulfilment_restrictions.ttl
-  13 implementation/eFulfilment/shacl_shapes/eFulfilment_shapes.ttl
-   1 implementation/eNotice/owl_ontology/eNotice.ttl
-   1 implementation/eOrdering/owl_ontology/eOrdering.ttl
-   6 implementation/eOrdering/owl_ontology/eOrdering_restrictions.ttl
-   7 implementation/eOrdering/shacl_shapes/eOrdering_shapes.ttl
-   1 implementation/ePO_core/owl_ontology/ePO_core.ttl
-  97 implementation/ePO_core/owl_ontology/ePO_core_restrictions.ttl
- 100 implementation/ePO_core/shacl_shapes/ePO_core_shapes.ttl
