### ISSUE TITLE
LotAwardOutcome hasRestatedAwardedValue MonetaryValue 

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#431]
why is the predicate hasRestatedAwardedValue needed?

**Comment by andreea-pasare** [comment]
This predicate was added for F20 standard form mappings:
![image](https://user-images.githubusercontent.com/88081600/221528098-602e30f3-eb17-46f7-99af-ca0976775a0b.png)
![image](https://user-images.githubusercontent.com/88081600/221871823-81407086-7444-4929-abfb-4b30928f4a75.png)

**Comment by andreea-pasare** [comment]
This is wrongly modelled and applied in the mappings. It will be updated in the context of modelling eContract.

**Comment by andreea-pasare** [comment]
ePO v4.0.0 allows the following:

![image](https://github.com/OP-TED/ePO/assets/88081600/d1a2d7ba-b5a6-4159-90af-091fa69833ab)
 1. epo-con:ContractAmendment epo:updatesContractValue epo:MonetaryValue
 2. epo-con:ContractAmendment epo:hasContractValue epo:MonetaryValue

![image](https://github.com/OP-TED/ePO/assets/88081600/0a6d014d-d83f-4fa0-aaa3-c16bd60240a1)

To ensure StandardForm mappings, the epo:updatesContractValue is used on the Amended Contract because if we go simply through Contract we do not know if it is the original Contract or if we had an Amended Contract in between times.
