### ISSUE TITLE
Invalid ttl file for ePO core

### ISSUE THREAD

**Issue by kvistgaard** [OP-TED/ePO#469]
There is at least an error on this line https://github.com/OP-TED/ePO/blob/b68b9005eb5af1e5e518235becf015e3eef19fcc/implementation/ePO_core/owl_ontology/ePO_core_restrictions.ttl#L127, but the full file needs to pass Turtle validation. There might be some invalid URIs.

**Comment by andreea-pasare** [comment]
This was fixed for the latest release candidate, ePO v4.0.0-rc3 tag: 
https://github.com/OP-TED/ePO/blob/v4.0.0-rc.3/implementation/ePO_core/owl_ontology/ePO_core_restrictions.ttl 

Indeed, there was a wrong value provided for an URI. Check the resolution of the following issue form model2owl repository: https://github.com/OP-TED/model2owl/issues/188

**Comment by kvistgaard** [comment]
@andreea-pasare , but that's the case also for the core ontology. The file in the master branch currently contains this line
https://github.com/OP-TED/ePO/blob/master/implementation/ePO_core/owl_ontology/ePO_core.ttl#L5809

**Comment by kvistgaard** [comment]
Seems that not on the TLL but the RDF?XML serializations has issues as well
`org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=157] Expecting rdf:RDF element.`

**Comment by cristianvasquez** [comment]
> This was fixed for the latest release candidate, ePO v4.0.0-rc3 tag: [`v4.0.0-rc.3`/implementation/ePO_core/owl_ontology/ePO_core_restrictions.ttl](https://github.com/OP-TED/ePO/blob/v4.0.0-rc.3/implementation/ePO_core/owl_ontology/ePO_core_restrictions.ttl?rgh-link-date=2023-10-26T12%3A22%3A50Z)
> 
> Indeed, there was a wrong value provided for an URI. Check the resolution of the following issue form model2owl repository: [OP-TED/model2owl#188](https://github.com/OP-TED/model2owl/issues/188)

@andreea-pasare, The problem was fixed in branch 4.0.0 but it persists in branch 4.1.0

I think the engine did not fail with malformed URIs in resources.

Effect: The RDF-XMl serialization is produced including a malformed URI, as seen here: https://github.com/OP-TED/ePO/blob/98e9dad5ef45682041587a5e69add8aa9a7bad0d/implementation/ePO_core/owl_ontology/ePO_core_restrictions.rdf#L77

When producing the turtle serialization it appears to be trunked: https://github.com/OP-TED/ePO/blob/98e9dad5ef45682041587a5e69add8aa9a7bad0d/implementation/ePO_core/owl_ontology/ePO_core.ttl#L5809

**Comment by andreea-pasare** [comment]
@cristianvasquez ePO v4.1.0 is not yet published. This is a work in progress, so the RDF outputs are not up to date yet.

**Comment by cristianvasquez** [comment]
Fixed in #475
