### ISSUE TITLE
GLOSSARY - Accelerated Procedure 

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#50]
#### Current Definition:

A process where the time limit for receipt of tenders can be reduced due to a state of urgency.

#### New Definition:

A procurement procedure where the time limit for receipt of tenders can be reduced due to a state of urgency or some administrative steps of the tendering procedure can be skipped due to a state of  emergency.

#### Reason:

The current definition is incomplete: The proposed definition covers the two cases for which the procedure can be accelerated: urgency and emergency.

**Comment by muricna** [comment]
Accelerated procedure: A procurement procedure where the time limit for receipt of tenders can be reduced due to a state of urgency 

Decision 18/04/2018
Reasoning the emergerncies mentioned in recital 100 deal with the exclusion criteria derogation and its use in the case of emergency this is not the same thing as accelerated procecure therefore maybe a new concept as stated below needs to be set up.

To discuss later possibility of separate and new concept that is not coverred by accelerated procedure such as:
Exclusion critera derogation: Emergency or some administrative steps of the tendering procedure can be skipped due to a state of emergency.
