### ISSUE TITLE
Wrong datatype for Notice `hasEFormsSubtype`

### ISSUE THREAD

**Issue by schivmeister** [OP-TED/ePO#554]
# Issue

An `epo:Notice` currently has the attribute (datatype property) `epo:hasEFormsSubtype` whose value range is `xsd:integer`.

<img width="159" alt="image" src="https://github.com/OP-TED/ePO/assets/1151152/a9d5ab9f-90c5-496e-a353-ee816517d5c4">

If the attribute is meant to represent a value from the `notice-subtype` vocabulary, the datatype is wrong, as [the vocabulary](https://docs.ted.europa.eu/eforms/latest/reference/code-lists/notice-subtype.html) also has string values:

```
CEI	
E1	
E2	
E3
E4
E5
T01
T02
X01
X02
```

# Recommendation

The value range for `epo:hasEFormsSubtype` shall be `xsd:string`.

**Comment by andreea-pasare** [comment]
The `epo:hasEFormsSubtype` is to be removed in ePO v5.0.0. This will tracked under a separate [issue](https://github.com/OP-TED/ePO/issues/560).

This attribute was an oversight on ePO's side. The classes to be used instead are in the eNotice module:
![image](https://github.com/OP-TED/ePO/assets/88081600/3dbf1a15-2a4f-4cc8-a4a9-6009d752fee5)
 

Regarding the second part of the ticket, the string code values mentioned are not used in the Competition Notices. They will be added before their mappings are required.

**Comment by andreea-pasare** [comment]
Implemented the following notice subtypes in ePO:
![image](https://github.com/user-attachments/assets/47c190cd-8736-40e7-b954-05127d4ebb50)
![image](https://github.com/user-attachments/assets/a73f97a6-5319-4b91-93c0-b103307bd3ef)
![image](https://github.com/user-attachments/assets/0a1e5730-5e7a-4d79-a125-3c16fdaad64f)
![image](https://github.com/user-attachments/assets/4aa3299d-8a70-4a36-af46-51eeb2d9395f)

`X01` and `X02` notice subtypes were not implemented since they are not used in public procurement.
