### ISSUE TITLE
Glossary - Buyer Profile

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#64]
This needs to be reflected as we have defined the buyer and this is more typically covered by the procuring entity

**Comment by paulakeen** [comment]
### Improvement of the term and definition

### Current Term: 

Buyer Profile

### Current definition: 

Website address where the buyer publishes information regarding procurement processes, such as procurement notices, contract award notices, prior information notices, etc.

### New Term: PROPOSAL: "PROCURER PROFILE"

### New Definition: 

Website address where the procurer publishes procurement documents such as notices, call for competitions, technical specifications,e tc.), clarifications, questions and answers, and other informations related to its procurement procedures.

### Reason: 

The data that is disseminated through the web site of a buyer profile is in fact always related to the procuring entity. The reason to name this "procurer profile" instead of "procuring entity profile" are:

1. The term "Procurer" is used in the Directive 2014/24/EU, Recital 2
2. The term "Procuring Entity" was introduced for the first time by "OCDS". The Directive's terms should prevail. 
3. In any case, the definition needs to be convened at new, as currently there's a big confusion between procurer, contracting authority, contracting entity and buyer.

**Comment by muricna** [comment]
WG 4/5/2018
Keep term as everyone knows what it is even if procuring entity/procurer would be better maybe a note could be added somewhere

Definition: Website address where the buyer publishes information on its procurement procedures  and general information

Concept

**Comment by eprocurementontology** [comment]
WG approval 4/05/2018

Term: Buyer Profile 
Definition: Website address where the buyer publishes information on its procurement procedures and general information.

The glossary and the conceptual model have been updated accordingly on 29/06/2018.
