### ISSUE TITLE
The subclasses of epo:Notice are missing in 4.x, while the change is not the the release notes

### ISSUE THREAD

**Issue by kvistgaard** [OP-TED/ePO#645]
In the latest ePO release epo:Notice has no subclasses.
At the same time, such a significant change is not mentioned in the [Release notes](https://docs.ted.europa.eu/EPO/latest/release-notes.html).
And the documentation still [shows subclasses](https://docs.ted.europa.eu/EPO/latest/_attachments/html_reports/eNotice/index.html). 
Both are on ... EPO/latest

**Comment by AchillesDougalis** [comment]
Hello,

> In the latest ePO release epo:Notice has no subclasses. 

As seen on the first image,   on the Master Branch (version 4.0.2)  of the [eNotice ](https://github.com/OP-TED/ePO/blob/master/implementation/eNotice/owl_ontology/eNotice.rdf)module, epo:Notice does have subclasses that are consistent with the documentation of the Notice module (image 2). Could the problem be that these subclasses do not appear in the [epo:core](https://github.com/OP-TED/ePO/blob/master/implementation/ePO_core/owl_ontology/ePO_core.rdf) module?
![2024-06-25_19-05](https://github.com/OP-TED/ePO/assets/143995053/28777365-9937-4b79-8203-4ea9426f4828)
![2024-06-25_19-16](https://github.com/OP-TED/ePO/assets/143995053/6130d44b-5e65-4971-a60d-a9b108a659e3)

**Comment by kvistgaard** [comment]
> Could the problem be that these subclasses do not appear in the [epo:core](https://github.com/OP-TED/ePO/blob/master/implementation/ePO_core/owl_ontology/ePO_core.rdf) module

Indeed, I was expecting it to be in the core.

Now I have a few questions before you close the issue:
1. Where can I read about the reasons for splitting the ontology into modules?
2. Why are the modules not published as TTL, as it is with the core?
3. Which file contains all `owl:imports` to compose the full ePO?

**Comment by AchillesDougalis** [comment]
1) The original reasoning for splitting the ontology can be found in  [WG meeting 7/1/21](https://docs.ted.europa.eu/epo-wgm/notes/2021-01-07-wgm.html) and   [WG meeting 14/12/21](https://docs.ted.europa.eu/epo-wgm/notes/2021-12-14-wgm.html), but we are currently in the proccess of reconsidering that idea. 

2) Every ePO module is available in both [XML/RDF](https://www.w3.org/TR/rdf-syntax-grammar/) and [Turtle/RDF](https://www.w3.org/TR/turtle/) formats.

3) There is not a single file containing all the `owl:imports` to compose the full ePO, because of the module structure.  In this structure, the ePO core module contains all the general concepts of the Ontology, and each other specialization module imports the core module. So to answer your question, It depends on how someone plans to use the Ontology. For example, if someone wants to use the Ontology for querying information on eForms, they should use the eNotice module. If someone wants to query information about the ESPD request, they should use the eAccess module,et cetera.

We realize that there is a lack in the documentation regarding how modules work, and we are currently  in the process of expanding the [documentation site](https://docs.ted.europa.eu/EPO/latest/index.html), so thank you for bringing this matter to light.

**Comment by kvistgaard** [comment]
Thanks. Well, I hope you'll decide to have one core file and the only other to be the one with restrictions.
