### ISSUE TITLE
GLOSSARY - Award Criterion

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ePO#78]
#### Current:

* Term: Award Criterion

* Definition: It describes a rule or a condition from the buyer that will be taken into account for the selection of the most economically advantageous tender, and which will be the basis for a comparative assessment of the quality of tenders.

#### New:

* Definition: Describes a rule or a condition issued by the Procuring Entity that will be taken into account for the selection and assessment of the quality of tenders.

*Additional Information*: An award criterion can be objective, when it can be evaluated following a formula, or subjective, when human analysis is required.

Examples of award criteria: the lowest price, the most economic tender, mixed (the most economically advantageous tender).

Lowest price
The most economic tender

#### Reason:

Rewording to make the definition consistent with the rest of the glossary and the ISO 11179 rules.

**Comment by guascce** [comment]
The directive uses the term 'Contract award criterion'. 
The definition and additional information is not consistently using 'Award  criterion' but also 'awarding'.
I disagree that the lowest price, the most economic tender, mixed (the most economically advantageous tender) are examples of award criteria.
Lowest price yes as the only criterion is the price.
MEAT is a method that involves a collection of award criteria and their weights.
In my view, award criteria have to be assessed. The selection results from the assessment and should not be part of the definition of the award criteria as the selection of tenders is also based on the evaluation of the tenderers. proposed changes
"Describes a rule or a condition defined in the procurement documents by the Procuring Entity that will be taken into account for the assessment of the tenders".

**Comment by muricna** [comment]
Do not need "in the procurement documents by the Procuring Entity" as this is adding embedded info which is not seen as good in the ISO standarded.

**Term: Award criterion
Definition: Describes a rule or a condition to be taken into account for the award decision
Concept.**

Reasoning the award decision was used in the definition because not all procedures end in a contract ie non-award or design contests.

**We need to add Award decision to the glossary at some time**

If you agree with this Enric please make necessary changes and close.

**Comment by paulakeen** [comment]
So the decision is that the definition would be:  "**Describes a rule or a condition to be taken into account for the award decision**".
