### ISSUE TITLE
GLOSSARY - Terms

### ISSUE THREAD

**Issue by sembu-rpam** [OP-TED/ePO#88]
#### Definition:

Conditions or stipulations limiting what is proposed to be granted or done.

Source: Random House Kernerman Webster's College Dictionary, © 2010 K Dictionaries Ltd. Copyright 2005, 1997, 1991 by Random House, Inc.

Examples:

tender submission terms, contract terms, financial terms, notifications terms, tender evaluation terms, etc.

#### Reason:
The same way we considered defining a very broad term as "justification", it is possible that we had the need of defining "Terms" in a broad sense (and in plural) to refer to pre-award and post-award terms that need to be taken into account in the procurement procedure life-cycle.

**Comment by JachymHercher** [comment]
I'm not a bit fan of the word "stipulations" - it seems very much as legal jargon. Since it's [not common](https://books.google.com/ngrams/graph?content=stipulation%2Crule%2Cobligation&year_start=1800&year_end=2018&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cstipulation%3B%2Cc0%3B.t1%3B%2Crule%3B%2Cc0%3B.t1%3B%2Cobligation%3B%2Cc0), wouldn't it be better to replace it with a more common synonym (e.g. rule, requirement)? Or perhaps simply remove it, because according to [some dictionaries](https://www.merriam-webster.com/thesaurus/stipulation) it's a synonym of "conditions"?

**Comment by muricna** [comment]
I would tend to agree

**Comment by muricna** [comment]
The concept term does not exist on its own.  There are for example procedure terms, submission terms etc.
