### ISSUE TITLE
Glossary - procuring entity, contracting authority and contracting entity

### ISSUE THREAD

**Issue by muricna** [OP-TED/ePO#95]
We need to check that we always use the same englobing term this may be difficult at times when definitions from the directives use a term that is not all encompassing but needs to be.

**Comment by JachymHercher** [comment]
Probably out of scope of the ontology right now, but just in case: don't forget that we have four types of "buyers" (=organisations launching a public procurement procedure; =organisations that can publish a procurement notice): contracting authorities, contracting entities, an organisation awarding a contract subsidized by a contracting authority (2014/24/EU Art. 13) and defence contractors (who publish the subcontract notice).

**Comment by muricna** [comment]
The term procuring entity has been used in the ontology and the term for buyers has been defined along the lines of OCDS and the eForms.  

However buyer is not modelled in the ontology and the procuring entity is not defined.  
The procuring entity is described under its conceptual model: 
"Procuring Entities are in general responsible for both the management of the procurement procedure and the purchase. However, in some cases procuring entities may buy on behalf of other procuring entities or through other procuring entities ("Procuring Entity Role Type")." 

The OCDS  definition of procuring entity is different:
 "The entity managing the procurement, which may be different from the buyer who is paying / using the items being procured."

I would like this to be discuss these issues and harmonise the concepts in our  conceptual model meeting of 5 September from 14h-16h at https://ecwacs.webex.com/meet/nmuric

**Comment by JachymHercher** [comment]
In eForms, the main ideas are the following:

Any organisation can have one or more roles (BT-08 Organisation Role):

- Buyer (Definition: the one who pays for the contract) 
- Central purchasing body (Definition: 2014/24/EU Art. 2(17))
- Procurement service provider (Definition: 2014/24/EU Art. 2(17))
- Contact point for additional information 
- Winner
- Review body
- EDIT: eSender

In turn, buyer's can be of several legal types (BT-11 Buyer Legal Type):

- Central government authority
- Regional government authority
- Local government authority
- Body governed by public law
- Buyer awarding a contract subsidized by a contracting authority
- Public undertaking
- Private undertaking operating on the basis of a special or exclusive right
- International organisation
- Defense contractor

(The values above can be grouped into contracting entities and authorities, e.g. for the purpose of business rules, main activity, etc. The subsidized buyer and the defense contractor are not a contracting authority nor entity.)  

From a conceptual model point of view, in my opinion, the "procuring entity" is an extra box that sits between "organisation" and "buyer"; conversely, the "buyer" is an extra box that sits between "procuring entity" and the "Buyer Legal Type" codelist. The function of these "extra boxes" is just aesthetic - to be able to easily refer to many things with one word.

**Comment by paulakeen** [comment]
The Working Group (WG  decision 28/09/2018) made the following decisions about the ePO Glossary and Conceptual Data Map:

# **ePO Conceptual Data Model**:

1. The class "Procuring Entity" will be removed;
2. Three classes are added: Buyer, Central Purchasing Body and Procurement Service Provider;
3. All three classes are associated to org:Organization (hence one individual of organisation, in different procedures, could act as Buyer or CBP or Service Provider);
4. All three may have their own Buyer Profile;
5. The Code Lists "Buyer Legal Type" and "Procuring Entity Type" are to be merged into one single code list (named "Buyer Legal Type");
6. The Main Activity Code List will be modified to reflext the dependency of the activity in respect of the type of bayer (e.g. CA.DEFENCE, CE.ELECTRICITY, etc.);

See diagram "[Buyer](https://github.com/eprocurementontology/eprocurementontology/wiki/Conceptual-Model-v2.0.1#buyer-)" in the Conceptual Data Model.

# **ePO Glossary**:

**Buyer** has been defined as: "Organisation that pays for the items being procured and may manage the procurement procedure."

**Central Purchasing Body** and **Procurement Service Provider** definitions were taken from the Directive 2014/24/EU. See these definitions in the [ePO Glossary](https://github.com/eprocurementontology/eprocurementontology/blob/master/v2.0.0/02_IR_DED/eProcurement_glossary.xlsx).

**Comment by JachymHercher** [comment]
A clarification about point 3: a CPB, when conducting activities in line with 2014/24/EU Art. 14(a), will also be a buyer. In this case, one organisation, in one procedure, will have both the role of a Buyer and a CPB. (This is useful, as it allows distinguishing CPBs conducting activities in line with 14(a) and 14(b).)

**Comment by paulakeen** [comment]
Thank you for the clarification Jáchym. From the implementation perspective of the ePO this is not a problem as the individual of org:Organization can be the same for one instance of Buyer and one instance of CPB. In which case the fact that both aggregate the same organisation allows to infer that Buyer and CPB are the same.

**Comment by JachymHercher** [comment]
I've been working on this subject in eForms some more and regrettably have some doubts about the buyer's definition of "Organisation that pays for the items being procured and may manage the procurement procedure." 

Back to the beginning: this term was created for eForms just as a shorthand for "a contracting authority, a contracting entity, an organisation awarding a contract subsidized by a contracting authority, a defence contractor or an international organisation, as appropriate." Defining it in any other way than given above may create unexpected problems down the line. I'm not sure why to take that risk if we just needed a shorthand, nothing more. 

For example, I'm not even sure whether "the one who pays" corresponds with "contracting authority". In cases of joint procurement, there could obviously be a case that just one contracting authority pays the contractor while the others will pay the chosen contracting authority. However, I cannot exclude that there could be a case when just one contracting authority would pay overall (for example, when a superior organisation would be buying something on behalf of many subordinate organisations), yet others would still be contracting authorities participating in the procedure. It's just a random example, but from legal experiences I've seen, these situations can become extremely complex. 

To make sure we don't stray from the directives' definitions, wouldn't it be better to simply: 
- remove buyer from the ontology, because everything can still be mapped to eForms just through BT-11 (Buyer Legal Type)? For example:
    - eForms: (Buyer Role = Buyer) + (Buyer Legal Type = Central Government Authority) = Ontology: Central Government Authority

or

- define buyer in the ontology as "a contracting authority, a contracting entity, an organisation awarding a contract subsidized by a contracting authority, a defence contractor or an international organisation, as appropriate. " (That would be an abstract class, sorry.)

___

Furthermore, talking from a data re-use point of view, the current way of explaining CPBs is a bit complicated: 
- If an organisation is a buyer and it is also a CPB, then it conducts activities in line with 2014/24/EU Art. 2(14a)
- If an organisation is just a CPB, then it conducts activities in line with 2014/24/EU Art. 2(14b). 

For eForms, I will suggest we collect this data directly as values of BT-08 (Buyer Role):
- "a buyer acquiring supplies and/or services intended for other buyers"
- "a buyer awarding public contracts or concluding framework agreements for works, supplies or services intended for other buyers"

**Comment by rantati7** [comment]
A quick response to @JachymHercher Indeed, the buyer is not always the one who pays for the goods / services / works. I support Jachym definition of buyer

**Comment by rantati7** [comment]
But instead of ”subsidised  by a contracting authority” I would say ”on behalf of a contracting autority / contracting authorities”. There could be additional definitions to CA, too. 

Please note: I do not like the term ”contracting authority / entity”. Buyer os better as it is plain language (not procurement jargon).

**Comment by JachymHercher** [comment]
@rantati7, just a small note: when we speak about "subsidised by a contracting authority", we are referring to organisations under 2014/24/EU Art. 13. I think "on behalf" is yet another concept (one that is ambiguous, because some have used it to denote what central purchasing bodies do, while others what procurement service providers do - both of which is defined in the directives).

**Comment by SellittoGiampaolo** [comment]
About the difference between Contracting Authority and Contracting Entity, it is traced in detail in the context of EU Directive 2014/25: in that Directive, Article 3 defines the term <<Contracting Authority>>: **‘contracting authorities’** means State, regional or local authorities, bodies governed by public law or associations formed by one or more such authorities or one or more such bodies governed by public law.
while Article 4 defines <<Contracting Entity>>: (for the purpose of this Directive) contracting entities are
entities, which: (a) are contracting authorities or public undertakings and which operate in the following fields: Gas and heat, Electricity, postal services, Transports, Ports and Airports and so on.
(b) when they are not contracting authorities or public undertakings, have as one of their activities any of the activities referred to in the directive, or any combination thereof and operate on the basis of special or exclusive rights granted by a competent authority of a Member State.Extraction of oil and gas and exploration for, or extraction of, coal or other solid fuels.

The insertion of an item to distinguish between the two kinds of buyers depends on the fact that Contracting Authorities as Buyers are subject to Directive 24, while Contracting Entities can profit from Directive 25, which is "lightweight" in most respects if compared to Directive 24.

**Comment by andreea-pasare** [comment]
In the latest release, ePO 3.0.1, the roles on the buyer side are modeled as depicted in the diagram below:
![image](https://user-images.githubusercontent.com/88081600/203260436-bb01d66d-89a0-4e91-ab91-98fb1a150c25.png)
